---
title: "Shared care"
author: "Pierre Walthéry"
date: "2023-06-09"
bibliography: /home/piet/Dropbox/work/CTUR/papers/shared_care/shared_care.bib
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract
Studies have shown how the sharing of childcare influences parental relationships, and the subjective well-being (SWB) of children. Yet not much is known about its direct association with parental SWB. Research on the involvement of fathers in childcare presents significant shortcomings: by not distinguishing between types of childcare; by relying on stylised measurements of the time spent caring, prone to measurement errors; by operationalising SWB via cognitive instruments (ie life satisfaction), unlikely to be affected by variations in daily circumstances.
Using the 2015 UK Time Use Survey on a subsample of dual-earning households, we modelled the association between the precise share of distinct types of childcare done by fathers and the daily enjoyment levels of parents, an innovative measure of SWB, using a Generalised Estimating Equation framework. Control variables included whether activities were recorded on weekdays or at the weekend and the time spent by fathers on childcare. 
Parental daily enjoyment was found asymmetrically associated with the share of childcare done by fathers: mothers reported an improvement when fathers took a moderate share, whereas a more substantial involvement was associated with higher levels of paternal SWB. Both were affected by the absolute amount of time parents dedicate to childcare.

# Introduction
Over the recent years, policymakers have shown a renewed interest for the division of caring roles between men and women in heterosexual families, and how these could be rebalanced. One driving reason for this lies in the part they play in the persistence of the gender wage gap, as the unequal division of unpaid care between men and women has been identified as its leading root (@GEO2019). The fact that women perform a ‘second shift’, as they still carry out - or are often expected to - most of the housework, household management and care roles within their families hamper their ability to compete with men on the labour market (@Hochschild1989). 
Although there has been an increase in the amount of time fathers spend with children (@Craig2014; @Gracia2015), a trend reinforced by the Covid-19 pandemic, the gender gap in childcare persists especially during the early years of a child’s life (@Fatherhood2016; @ONS2020). At the same time, a growing number of fathers, especially among the younger generation, express the wish to be more involved in care-giving, even if this means sacrificing some of their earnings in the process (@Working2017; @Burgess2021). 
Societal expectations requiring fathers to be breadwinners and mothers caregivers (@Scott2013; @Taylor2018) and the fear that involvement in childcare will negatively affect their career prospects (@Chung2018) explain why fathers still feel unable to contribute more. Similarly, women’s decisions to engage in paid work remain influenced by traditional gender norms, such as the view that preschool children will suffer if their mother work, and that family life suffers when a woman has a full-time job (@Scott2013). In order to alter social representations about the respective involvement of mothers and fathers in childcare, it is necessary to scrutinise the beliefs about paternal participation in childcare and its consequences.
Previous research has challenged these norms by providing evidence of the positive outcomes for children of fathers’ involvement in childcare, (for a review, see @Allen2007a; @Chung2021) as well as for the stability of and satisfaction with the parental relationship (@Norman2018; @Schober2012, @Schober2013). 
However, these studies restricted the measurement of father’s involvement in childcare to specific activities according to the age of their children (e.g., @Huerta2014; @Kroll2016; @Nomaguchi2017; @Norman2018; @Twamley2013). Such approaches not only overlook the actual amount of time fathers spend on childcare, but also how it is shared between parents. 
Among contributions that rely on the time spent with children as a measure of involvement (e.g., @Baxter2011), many do not distinguish between different categories of care – e.g. routine vs non-routine, solo vs. joint care. Being able to distinguish between these is crucial in order to identify factors that may encourage fathers to dedicate more time caring as the main caregiver, which is critical in supporting mothers’ labour market participation. 
Finally, among the limited number of studies that have focused on the well-being of parents, most (e.g. @Glass2016; @Schober2016) have relied on cognitive instruments to capture it – typically, life satisfaction. A potential downside is that these tend not to be responsive to short or medium-term changes in one’s circumstances, such as day-to day variation in the share of childcare carried out by each parent. Studies have also tended to focus directly on the negative outcomes of the division of childcare, for example, marital satisfaction and dissolution (e.g., @Frisco2003; @Norman2018; @Ruppanner2018; @Schober2012; @Schober2013), stress and negative well-being outcomes (@Milkie2002; @Nomaguchi2017) rather than investigating its broader positive and negative impacts, in particular on well-being. 
This paper aims to fill some of these gaps; first, by exploring how the time fathers spend with children is associated with short-term variations in their well-being. We were able to do so by using an innovative instrument captured in time-diaries namely daily enjoyment, as a well-being indicator. Finally, by using the 2015 UK Time Use Survey, we were able to investigate examine the share of the time spent by fathers looking after children within the household, separately for different types of childcare. 

# Background
## Typologies Of Care
Craig and Mullan (2011) have argued that when trying to assess the impact of childcare on outcomes, relying on the total time spent caring by each parent is insufficient. Examining how parents share different types of childcare is necessary in order to understand its gendered dynamics. Furthermore, as childcare can be recorded as a caregiver’s main- or secondary activity, for example, alongside housework or paid work, it is important to take both types into account (@Craig2011).

Mothers are more likely to provide childcare, but also to be responsible for its routine aspects, whereas fathers are more likely to engage in the non-routine types of care (@Craig2006; @Craig2011; @Craig2011a). Routine childcare entails the physical care of children, such as feeding, cleaning/bathing, routine bedtime activities, or taking children to school. Non-routine or enrichment/educational care involves talking, reading and play-centred activities. They are labelled as ‘enrichment’ as they augment a child’s capital of experiences for educational purposes. Only when fathers take on some of the more rigid routine care duties, which are more likely to conflict with work schedules, can mothers be relieved of some of the pressures affecting their ability to meet their work demands. Fixed family routines (such as school drop off/pick up and mealtimes) combined with inflexible work schedules will limit women’s ability to step up their participation in paid work (Chung & van der Horst, 2018). In contrast, playing with and reading to children fit more easily a parent’s schedule, and may not pose as much of a barrier towards involvement in paid work. 

In this study, we chose to  study childcare when carried out by a parent on her/his own rather than alongside the other parent as in the latter case, the time fathers spend on childcare does not free mothers to conduct other pursuits. Craig (2006) also argues that when mothers and fathers jointly look after children, mothers tend to assume the primary responsibility for it, whereas father keep a supporting role. Consequently, the mental load of planning and managing childcare in such cases disproportionately remains on mothers (see also @Walzer1996). 

## Shared care and parental subjective well-being
Commonly defined as “a broad category of phenomena that includes people's emotional responses, domain satisfactions, and global judgments of life satisfaction” (@Diener1999: 277), Subjective Well Being (SWB) is often associated with socially desirable outcomes, be it job- or health related (@Lyubomirsky2005; @Pressman2005). Whereas the evaluative/cognitive dimension of SWB such as life satisfaction has been the focus of most of the literature, possibly due to the wide availability of instruments in mainstream social surveys, the more versatile affective side of SWB has been lagging, with few large-scale study considering this aspect.

Studies found patterns of association between SWB and involvement in childcare as well as how childcare is shared between parents. An unequal division of childcare has been associated with low relationship satisfaction and marital dissolution across several countries (@Carlson2016; @Kalmijn1999; @Norman2018; @Schober2012) largely due to its impact on parental well-being and stress levels. As they are generally responsible of a larger share of childcare and housework (@Taylor2018), mothers, and especially working mothers are more likely to experience low well-being as a results of the pressures coming from work and family demands (@Chandola2019; @Ruppanner2018). 

Ruppanner et al. (2018) found that although both parents experience time pressure following the birth of children, mothers do so more than fathers. This may result in a deterioration of their mental health in particular for those with two or more children. It could therefore be inferred that relieving mothers from the demands of childcare and housework could improve their stress levels. A study comparing parental happiness across 22 countries found that parenthood was not associated with lower levels of happiness in countries with generous state support for parents(@Glass2016) . Similarly, Schober & Stahl (2016) showed how the expansion of full-time childcare facilities in Germany was associated with mothers experiencing greater satisfaction with family life, and with life overall. In sum, improved maternal well-being levels can be expected where support for childcare responsibilities is present. This can originate from state policies, but also from fathers taking on a larger share of childcare. 

Although parenthood often brings about increased stress-levels and is linked to lower life satisfaction, it also can impact positively well-being. Negraia and Augustine (2020) using data from the American Time Use Survey found that when carrying out their daily activities, parents expressed higher levels of happiness than non-parents, and that this was largely driven by having a child present. In addition to being a source of love and intimacy, children may provide adults with opportunities to feel valued as they perform a socially desirable role as parents. (@Nomaguchi2003; @Negraia2020). This may be especially true for fathers, as mothers already take on the bulk of childcare. In fact, fathers who are involved in childcare have been shown to experience greater job satisfaction, work-family enrichment, and less work-family conflict (@Ladge2015). 

As it mostly consists of playful and stimulating activities, enrichment childcare is likely to be the type of childcare most enjoyed by parents (@Craig2014). This may be especially the case for fathers, as enrichment activities seems to readily fit in with representations of the caring masculinity identity (@Brandth1998). Conversely, fathers’ involvement in the more “feminine” routine childcare may not necessarily be associated with improved well-being. 

On the other hand, one could expect that given the prevailing imbalance between parents, sharing any type of care would have a positive impact on mothers’ well-being. It may also be that a more even balancing of routine childcare between parents will be especially impactful on mother’s well-being (@Nomaguchi2017). When fathers take on a greater share of routine childcare mothers might feel relieved of the time-pressures they often experience (@Chandola2019).

## Summary And Hypotheses
Our overall hypothesis is that the greater the share of childcare taken on by fathers, the larger the improvement in well-being for mothers and fathers, particularly daily enjoyment. We would expect that a more balanced sharing of childcare, especially routine childcare, would improve maternal well-being by reducing their time-pressure and stress levels. We expect father’s well-being and enjoyment levels to increase as they are able to spend more time doing childcare, and taking on a larger role, especially in enrichment/non-routine childcare. 

# Data And Methods
## Data
This study relies on the 2015 UK Time Use Survey (TUS). The TUS is a two-stage stratified random sample survey representative of non-institutional households in the UK. Data was collected through self-completed time diaries and face-to-face individual questionnaires. The time diaries recorded all activities in ten minutes slots over two 24h periods – one weekday and one day at the weekend. Respondents also recorded the location of activities, the presence of other people, their enjoyment level, and whether other, secondary activities took place at the same time. The diary days were randomly allocated over a period of one year and identical for all members of same household. Overall sample size is 11,421 individuals in 4,733 households. Of these, 8,210 individuals in 3,606 households provided complete time diary information.
## Sample
The population of reference was defined as the days (in 2014-15) of UK households made of two cohabitating heterosexual adults with at least one child aged between 0 and 14, who were both employed, and during which at least one of the two parents recorded childcare-related activities in their time diary. The analysis was conducted on a matched household sample, where data from mothers and fathers were joined together. Single parent households, and households made of several families with children or multi-generational households were not retained, as relatives could provide care for children and interfere with the parenting dynamic studied here. Actual sample size was 568 days recorded in 284 such households with non-missing information about well-being and caring for children in the time diaries (1,140 days when including those with missing information). Such a reduced size constitutes one of the main limitations of our study as it limits the power of multivariate analysis and significance testing. It nonetheless remains a valid random sample from which inferences to the days of UK households can be made, albeit with caution.

## Dependent Variables
Experienced well-being.
Enjoyment of the activities reported in the time-diary was recorded on a scale ranging from 1 to 7. Due to limited sample size, it was decided not to break down enjoyment by types of childcare but instead to rely on an overall daily estimate. We computed it as the mean level of enjoyment of all non-resting activities over the course of a full day. For technical reasons, enjoyment in the UK TUS was only recorded from October 2014, resulting in about 25% item non-response. Another limitation of this study is therefore that sample sizes vary slightly between well-being outcomes.
 Evaluative well-being and life satisfaction. 
In order to enable for our results to remain comparable with other studies, we also used traditional measures of cognitive well-being.
    • Life Satisfaction: Overall, how satisfied are you with your life nowadays?
Answers range on a scale from 0 (Not at all) to 10 (Completely). This indicator is widely used in social science. It is also currently part of the Office for National Statistics’ Personal and Economic Well-being indicators series (ONS 2019). For technical reasons, the scale of the variable was changed during fieldwork from seven to ten items. As a result, we decided to standardise then merge both variables into a single one, in order to avoid a loss of observations.
We also chose two facets specific indicators of well-being directly relevant to childcare and parenting, with answers ranging on as scale from 1 (Completely dissatisfied) to 7 (Completely satisfied)
    • Work-life balance satisfaction: How dissatisfied or satisfied are you with your work-life/work-family balance?
    • Satisfaction with social life: How dissatisfied or satisfied are you with your social life?

## Independent variables
Fathers share of childcare
Our main independent variable is the amount of time spent by fathers on childcare relative to the total time spent looking after children in the household on a given day. We broke down childcare time according to the types developed above; routine vs non-routine/enrichment care (@Craig2011), as well as whether it was provided by parents on their own – i.e., solo care, again excluding joint care in our analysis. We used a fourth type, primary childcare, defined as childcare recorded as main activity in order to capture the overall association between parental well-being and any childcare.
 Table 1 provides a description of these different types in our data. Solo care was defined as care provided the parent when the other parent was not present at the same time. Primary childcare was operationalised, as childcare provided as main (ie primary) recorded activity in the diary.

Table 1. Categories of care
Category
Concept
Types included
Type of care given
Routine
Feeding, bathing, dressing, putting to bed, carrying, soothing, transport to school as primary or secondary activities

Enrichment/non routine care
Talking, listening, teaching, helping children learn, reading, telling stories, and playing games etc.. as primary or secondary activities
Involvement of the other parent
Solo care
When care is provided as primary or secondary activities without the other parent involved, 
Primacy of care
Primary
Any childcare provided as the main activity by the parent, with or without other recorded activities

For each one of these types, the number of minutes fathers spent caring was divided by the total caring time spent by mothers and fathers within each household then multiplied by 100. In order to account for the likely nonlinear effect of this variable on well-being, we derived a three-category ordinal version consisting of: fathers not doing any childcare on diary day (reference category); fathers taking on less than 40% of the childcare; fathers taking on 40% or more of the childcare. The cutting point was set at 40 % rather than 50% in order to alleviate the small number of fathers caring more than 50% of the time.

## Modelling Strategy
We examined the bi- and multivariate association between the share of childcare taken on by fathers and well-being outcomes for mothers and fathers respectively, broken down by types of care. As observations consist of two days by respondent, regression results might be unreliable as the assumption of independence is violated. For this reason, we used a Generalized Estimating Equation model approach, a technique which has been shown to provide robust average estimates of the main effects (@Gardiner2009; @Zeger1988) in such cases. GEE models are robust to misspecification of the within person correlation structure of the error terms and the presence of small size cluster (@Skrondal2004). Fixed effect regression would not be appropriate here as in all but one case the outcome remains invariant within respondents and also the size of the respondent-level effect is not of substantive interest here. 

## Control variables
We controlled for the socio-demographic characteristics of respondents, as they are known to influence the time spent on childcare (@Craig2011) and well-being (@Kroll2016; @Milkie2002; @Schober2012): parental education; household-level working-time configurations (one parent part-time, the other full-time, or both parents working full-time); age; and whether the day was a weekday or at the weekend. We also controlled for the absolute amount of time spent by mothers on childcare as it could influence the effect of sharing between parents. One could imagine for instance that the amount of childcare done by fathers could potentially have more impact on a day mothers are particularly busy with childcare.

# Results
Table 2 presents the main characteristics of the matched sample of working parents. 
Table 2. Sample characteristics

Mothers
Fathers

%
N
%
N
Higher education
53
302
39
198
Secondary education
14
72
15
85
Below secondary education
33
194
45
278
Full-time-No flexible working time
19
104
58
333
Full-time+Flexible working-time
25
143
36
201
Part-time-No Flexible working-time
27
157
4
18
Part-time+Flexible working-time
29
164
2
16
Age
35
568
38
568

%
N
Both parent work full-time
39
225
Father full-time-Mother part-time
55
309
Other working-time arrangements



Other
6
34
Youngest child is 0-4
74
420
Youngest child is 5-10
25
141
Youngest child is 11-15
1
5
Socio-demographic characteristics of the matched household sample N= 568 days, 284 households. Data: UK TUS 2015

We can see that on average respondents tend to be more educated than the general population. The educational discrepancy between mothers and fathers is probably down to the fact that employed mothers tend to be more educated that those economically inactive. Also worth noting, even if unsurprising, the discrepancy between mothers and fathers in terms of flexible working-time provisions: close to 53% of households have women working some form of flexible hours (29+25%), whether on a full or part-time contract, against 38% of fathers having the same arrangements (26+2%). In most households (55%) mothers worked as secondary earner whilst fathers worked full time, against 39% of dual earner (both parents work full-time) households. Finally, 74% of households had at least one child below primary school age, which is not surprising given that these require the largest amount of caring and the sample selection required days in which as least one episode of childcare was recorded in the diary. For the same reasons, the number of households with children aged 10 or above is negligible.

Table 3. Proportion of childcare carried out by fathers in dual-earner families by categories

Not caring
Less than 40%
40% and more

%
N
%
N
%
N
Primary caring
28
156
45
244
27
146







Solo caring
55
299
29
159
16
87







Routine caring
32
174
50
271
18
100
Enriched caring
48
259
41
259
11
62
Any caring
23
127
40
219
37
200
Socio-demographic characteristics of the matched household sample N= 568 days, 284 households. Data: UK TUS 2015

Table 3 gives a first overview of the sharing of childcare between fathers and mothers in the sample. We can see that between 28 and 55% of fathers did not take part in any type of childcare on the day diaries were recorded. 72 % (45+27) of fathers in the sample reported engaging in primary childcare, with about one quarter reporting taking on 40% or more of the childcare. Interestingly 68% of fathers in the sample did some routine care against 52% who engaged in enriched care. This could be related to the fact that our sample is made of dual earners couples, which tend to have higher levels of qualification, and therefore fathers engaging more in childcare of any type (see also, Dotti Sani & Treas, 2016).
Unsurprisingly, there was no type of caring that a majority of fathers undertook more than mothers. The proportion of fathers reporting at least 40% of the childcare time in households in the sample ranged from 11% (enriched caring) to 27% (primary caring). In most cases a larger proportion of fathers (between 29% and 50%) took between 1 and 40% of the total amount of care given that day. It should be noted that these proportions vary according to whether the diary was recorded on a weekday or at the weekend: whereas 25.4% of fathers in the sample reported not doing any childcare on weekdays, only 18.6% did so at the weekend (not shown).
Table 4. Mean immediate and evaluative well-being

Mothers
Fathers

Mean
N 
Mean 
N
Daily levels of enjoyment
5.8
248
5.6
266
Life satisfaction
0.2
289
0.1
204
Work-life balance satisfaction
4.8
525
4.8
371
Satisfaction with social life
4.9
525
4.8
371
Means of various well-being outcomes in the matched household sample N= 568 days, 284 households. Data: UK TUS 2015. Outcomes range from 1 to 7, except for life satisfaction for which scores were standardized.

Finally, Table 4 shows an overview of the outcome variables for mothers and fathers: daily levels of enjoyment, life satisfaction, as well as satisfaction with partner and work-life balance satisfaction. Means tend to be similar albeit slightly higher for mothers. The number of observations is clearly higher for mothers than fathers with the exception of daily enjoyment.

## Multivariate Analysis
GEE models were fitted to the data, in order to examine the association between the share of childcare taken on by fathers and parental well-being. As expected, significant positive associations were found with daily enjoyment rather than the cognitive instruments, but only for fathers. No significant association were found between fathers’ share of childcare and life satisfaction. Weaker associations (p<.1) with work-life balance satisfaction and satisfaction with social life were found, respectively positive and negative. The absolute amount of time mothers spent looking after their children (rather than their share) was found more strongly associated with maternal well-being outcomes rather than father’s share per se.

###	Mothers.
Table 5 shows no significant association between the well-being of mothers and the share of childcare done by fathers, once socio-demographic variables, as well as the absolute amount of time they spend on childcare are controlled for. Rather unexpectedly, the daily enjoyment of mothers increased with the time they spent on solo and enrichment childcare, in the latter case a strongly significant relationship (respectively .09 p<.05 and .12 p<001). A similar result was observed with life satisfaction and the time mothers spent on routine childcare. In other words, the actual time mothers dedicate to childcare seems to have a more significant impact on their well-being than the share that is done by fathers. 

Before control variables were introduced a weakly significant positive effect on maternal daily enjoyment was observed in households where fathers took on between 1 and 40% of primary childcare (not shown). These results might suggest that the positive association between fathers’ share of childcare and their partner’s well-being could hold only for some duration of childcare. We explored this interpretation by introducing an interaction term between the two variables. Results are shown in Table 6.

The picture emerging is that there is a strongly significant association between both the daily enjoyment of mothers and their life satisfaction on the one hand, and the time they spend looking after their children – but only in households when fathers take on more than 40% of either the primary or solo childcare workload. The coefficients are respectively .32 and .49 p<.001 for daily enjoyment, and .31 and .48 p<.01 for life satisfaction. A similarly strong association with life satisfaction was found in the case of routine childcare (.60 P<.001) and with daily enjoyment and enrichment care (.14 p<.001). This suggests that the share of childcare taken on by fathers has a clear bearing on the way the well-being of mothers is affected by looking after their children.

Table 5. GEE models of parental well-being by fathers share of childcare 

Mothers
Fathers

Primary
Solo
Routine
Enriched
Primary
Solo
Routine
Enriched

Daily enjoyment
Paternal share <40% (ref. 0%)
.18
.13
.15
.11
.15
.04
.17
.03

(.11)
(.10)
(.10)
(.09)
(.12)
(.11)
(.12)
(.10)
Paternal share >=40%
.10
-.04
-.06
.01
.41***
.14
.19
.30*
 
(.12)
(.14)
(.14)
(.12)
(.12)
(.13)
(.13)
(.12)
Time mother spent on childcare
.08·
.09*
.08
.12***
.08*
.00
.03
.04
 
(.05)
(.04)
(.06)
(.04)
(.04)
(.04)
(.05)
(.04)

Life satisfaction
Paternal share <40% (ref. 0%)
-.03
.01
.01
.03
-.05
-.17
.11
.09
 
(.14)
(.12)
(.13)
(.12)
(.15)
(.15)
(.17)
(.12)
Paternal share >=40%
-.03
-.13
-.10
-.04
-.02
-.26
-.09
-.14
 
(.18)
(.19)
(.18)
(.16)
(.17)
(.21)
(.21)
(.24)
Time mother spent on childcare
.13*
.09·
.08
.06
.14*
.13*
.08
.06
 
(.06)
(.05)
(.06)
(.04)
(.07)
(.05)
(.07)
(.05)

Work-life balance satisfaction
Paternal share <40% (ref. 0%)
-.15
.05
.02
.01
.08
-.09
.18
-.01
 
(.20)
(.17)
(.19)
(.17)
(.24)
(.18)
(.23)
(.18)
Paternal share >=40%
.17
-.01
-.15
.39+
.29
.13
.15
.35
 
(.22)
(.20)
(.24)
(.22)
(.24)
(.20)
(.23)
(.23)
Time mother spent on childcare
.16·
.07
-.01
.07
-.06
.01
-.13
.07
 
(.09)
(.07)
(.10)
(.08)
(.10)
(.09)
(.13)
(.08)

Satisfaction with social life
Paternal share <40% (ref. 0%)
-.18
-.22
-.11
-.26+
.28
-.10
.12
-.05
 
(.17)
(.15)
(.16)
(.15)
(.23)
(.19)
(.24)
(.19)
Paternal share >=40%
-.06
-.14
.07
.02
.35
-.20
.37
.01
 
(.19)
(.19)
(.19)
(.20)
(.26)
(.22)
(.26)
(.24)
Time mother spent on childcare
-.14·
-.06
-.04
-.09
-.15
-.02
-.11
.02
 
(.08)
(.07)
(.08)
(.08)
(.11)
(.08)
(.12)
(.09)
***p < 0.001; **p < 0.01; *p < 0.05; +p < 0.1. Matched household-level dataset of parents aged 16 and above in heterosexual couples with at least one child under 15. data: UK TUS 2015 Coefficients denote the change in the specified well-being scale. Standard errors between brackets. 


As table 5 shows, the work-life balance satisfaction of mothers, and to a lesser extent, their satisfaction with social life were found associated with the share of childcare taken on by fathers, but these relationships were only significant at p<.1. In households where fathers took on a moderate amount of enriched childcare (up to 40%), mothers expressed worse level of satisfaction with their social life (-.26) whereas in households where fathers took on a substantial amount of enriched childcare (more than 40%), mothers report being happier with their work life balance (.39). 

### Fathers.
Unlike  mothers, we found a direct association between the daily enjoyment of fathers and the share of childcare they take on. As Table 5 shows, father’s daily enjoyment was higher in households where they spent more than 40% of the time doing childcare as a primary activity (.41), and this relationship is strongly significant (p<.001). Similarly, it was also higher in households where they did take on more than 40% of the time on enrichment childcare (.30, p<.05), which confirms our expectations.


Table 6 GEE models of SWB & ` – interactions between duration and sharing
 
Mothers
Fathers

Prim

Solo
Rout
Enrich
Prim
Solo
Rout
Enrich
Ref: no time on childcare 
Daily enjoyment
Mother’s time on childcare*father’s share<40% 
.03

.07
.03
.14***
.10+
.01
.02
.01

(.07)

(.09)
(.08)
(.04)
(.05)
(.07)
(.06)
(.05)
Mother’s time on childcare* father’s share>=40% 
.32***

.49***
.19
.06
.16
-.27
.12
-.06

(.09)

(.12)
(.16)
(.10)
(.11)
(.37)
(.12)
(.11)
Ref: no time on childcare
Life satisfaction
Mother’s time on childcare*father’s share <40% 
.12·

.09
.04
.03
.00
.12
-.01
.07

(.07)

(.09)
(.07)
(.05)
(.09)
(.09)
(.06)
(.07)
Mother’s time on childcare* father’s share >=40% 
.31**

.49**
.60***
.01
.40**
.33*
.36·
-.28

(.11)

(.17)
(.15)
(.22)
(.15)
(.13)
(.21)
(.22)
***p < 0.001; **p < 0.01; *p < 0.05; +p < 0.1. Matched household-level dataset of parents aged 16 and above in heterosexual couples with at least one child under 15. data: UK TUS 2015. Coefficients denote the change in the specified well-being scale. Standard errors between brackets.

We also explored the interaction between the amount of time spent on childcare by mothers and the share taken on by fathers on paternal well-being. We found marginal evidence of a positive interaction between sharing of primary childcare and the amount of time mothers care for children. In other words, as mothers’ time on childcare increases, fathers experience higher levels of daily enjoyment, but only if they provide a moderate (up to 40%) contribution to primary childcare (.10, p<.1). Stronger interactions, in line with those observed among mothers were found with the life satisfaction of fathers. As the time mothers spent on childcare increased, a contribution of fathers greater than 40% to either primary or solo childcare significantly increased their life satisfaction (respectively .40 p<.01 and .33 p<05). As expected, no significant association was found between the well-being of fathers and their involvement in routine childcare.

###	Role of control variables
Comparing the above models with and without covariates gave some indication of the pattern of association between socio-demographic factors, childcare sharing and well-being. Controlling for whether caring occurred during a weekday or at the weekend reduces the coefficient and significance of enrichment care on well-being: in other words, the positive impact of fathers spending time on enriched care might in fact be partly due to the fact that it predominantly occurs at the weekend, a time during which daily enjoyment tends to be higher for all. 

As we already saw, controlling for the absolute amount of time spent by mothers on childcare made initially significant associations between fathers’ share and the daily enjoyment of mothers, become non-significant in some cases. This in turn enabled us to unearth significant interactions between the two variables. These suggest that a large share of childcare taken on by fathers has a positive impact on maternal daily enjoyment as mothers’ time spent looking after children increases. On the other hand when mothers spent increased amounts of time on childcare, it is only when fathers took on a modest share of it that their daily enjoyment improved.

# Discussion And Conclusion
This paper examined how the division of childcare between mothers and fathers in dual earner couples with children was associated with parental well-being levels using time use diaries. By contrast with previous studies, we were able to look at the actual time mothers and fathers spent looking after their children and the way this was shared between them, specifically exploring the share of total childcare time taken on by fathers. We investigated the differences in well-being according to the type of childcare that was shared – i.e., routine vs. enrichment, primary, solo childcare. We were able to rely on an innovative instrument measuring immediate well-being – the overall level of enjoyment parents felt during the day – in addition to more established indicators of cognitive well-being such as life satisfaction or satisfaction with social life, and work-life balance satisfaction.

One important result presented in this paper is that despite the reported increase over the years in the time spent caring by fathers, a large proportion of men in the sample did not report any type of childcare during their day – approximately a quarter of the days in the sample. Furthermore, almost half did not record taking part in any enrichment care or any solo care, where care was provided by the fathers alone without the mother involved. Very few fathers took an equal share or more (40% and above) of caring. 
We found evidence that the involvement of fathers in childcare may help improve a mother’s well-being especially for daily enjoyment and life satisfaction. When fathers carry out a significant share of the primary and routine childcare, mother’s time spent looking after children is positively associated with their own well-being. 

We found a more consistent association between a father’s involvement in childcare and their own well-being. There was a clear indication that a more equal sharing of childcare – when fathers were responsible for 40% or more of the total time spent on primary childcare in the household – made a difference in raising their level of well-being, by contrast with fathers who were not involved. Similarly to previous studies, we found that fathers who were intensively involved in enrichment childcare were those who were enjoyed their day more, and were more satisfied with their work-life balance. 

This leads us to an interesting conclusion. Much of the discussion around the sharing of childcare so far has been driven by its impact on gender equality, namely how a more equal distribution of caring roles can help women fully compete with men in the commodified labour market. However, as this study and some previous studies have shown (@Ladge2015; @Negraia2020), getting fathers more involved in childcare may also improve men’s (mental) health. Masculinities and men’s identities are shifting as society’s ideas of gender roles change and demands of men and fathers change (@Brandth1998). What our study has shown is that we need to think about men’s involvement in childcare as being instrumental to improve their well-being. Men should be allowed to expand their roles as carers not only to ensure that they are able to meet their duties as involved fathers, and equal partners in parenting, but also because it benefits their mental health, and as a result, possibly their overall health and well-being in the long term as well. 

These results also add to our knowledge of the association between the sharing of childcare and maternal well-being. Previous studies have predominantly relied on instruments recording cognitive well-being, which remains at arms’ length from respondents daily emotional experiences. Our study shows that father’s involvement in childcare has a positive impact on the immediate well-being of both parents, as measured by their daily enjoyment levels. Although limited, these results seem to suggest that beyond the traditional reasoned assessments mothers and fathers make of their satisfaction with their life, the daily flow of emotions which is also an important component of subjective well-being is affected by the share of childcare that is being taken on by fathers, and in fact perhaps more so. Judging by the results we presented above, daily levels or enjoyment were found to be as consistently associated with the sharing of childcare as traditional cognitive instruments.

The paper is not without its limitations. To start with, the small sample size hampers the precision of the results presented here. Future studies should be conducted, preferably with larger sample, to examine the extent to which these results can be replicated. Another issue is the fact that the instrument we used for measuring daily enjoyment remains rudimentary. Although it obviously represents a clear improvement over the previous lack of measurement of immediate well-being in large scale social surveys, it does not currently capture negative emotions, or the extent to which positive or negative emotions leads to stimulation or excitement (@Warr2007). 

These findings have significant implications for government and corporate policies. Many governments have been pushing for greater involvement by fathers in the care of their children, for instance, by increasing the size of the fathers-only portion of parental leave (see also the new European Commission’s Work-life balance directive). Much of these tend to aim to increase the size of the female workforce and fully exploit the female human capital potential. This paper shows that the conversation also needs to focus on enhancing parental well-beingof fathers and men’s in addition to that of mothers. This can reinforce the case for implementing such policies: which are not only necessary for sustaining economic growth or for women’s rights per se, but also to enhance the well-being of both men and women. 

Our results also have implications for companies and managers. We know from the organizational studies literature that workers who are happy and have better work-life balance will be more productive in companies (@Leslie2012). Whilst retaining female workers is considered to be the main raison d'être of fathers’ involvement in childcare, this may not provide sufficient incentives for employers of fathers. Increased maternal labour force participation may benefit other companies. However, as we can see from the results of our study, supporting fathers to play a larger role in the care of children can improve their well-being which can directly relate to worker’s productivity. 

Finally, our study carries an important message to fathers and mothers. Fathers may be reluctant to use leaves and flexible working arrangements to be more involved in the care of their children due to the stigma it carries (@Rudman2013), and for fear of experiencing disadvantage in their career. However, the message that “taking on a larger part in the care of children may be beneficial for your well-being”, especially compared to that of households with more traditional division of labour may contribute to changing this idea. Our study confirms that sharing the two roles equally may contribute to healthier relationships and more enjoyable days. 

# References

