<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pierre Walthéry &amp; Heejung Chung">

<title>Childcare sharing and parental well-being</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="2025_resub_files/libs/clipboard/clipboard.min.js"></script>
<script src="2025_resub_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="2025_resub_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="2025_resub_files/libs/quarto-html/popper.min.js"></script>
<script src="2025_resub_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2025_resub_files/libs/quarto-html/anchor.min.js"></script>
<link href="2025_resub_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2025_resub_files/libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2025_resub_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2025_resub_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2025_resub_files/libs/bootstrap/bootstrap-03f9820e10548af6580ffe761ed5fad7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a>
  <ul class="collapse">
  <li><a href="#typologies-of-care" id="toc-typologies-of-care" class="nav-link" data-scroll-target="#typologies-of-care">Typologies Of Care</a></li>
  <li><a href="#shared-care-and-parental-subjective-well-being" id="toc-shared-care-and-parental-subjective-well-being" class="nav-link" data-scroll-target="#shared-care-and-parental-subjective-well-being">Shared care and parental subjective well-being</a></li>
  <li><a href="#summary-and-hypotheses" id="toc-summary-and-hypotheses" class="nav-link" data-scroll-target="#summary-and-hypotheses">Summary And Hypotheses</a></li>
  </ul></li>
  <li><a href="#data-and-methods" id="toc-data-and-methods" class="nav-link" data-scroll-target="#data-and-methods">Data And Methods</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#sample" id="toc-sample" class="nav-link" data-scroll-target="#sample">Sample</a></li>
  <li><a href="#dependent-variables" id="toc-dependent-variables" class="nav-link" data-scroll-target="#dependent-variables">Dependent Variables</a></li>
  <li><a href="#independent-variables" id="toc-independent-variables" class="nav-link" data-scroll-target="#independent-variables">Independent variables</a></li>
  <li><a href="#modelling-strategy" id="toc-modelling-strategy" class="nav-link" data-scroll-target="#modelling-strategy">Modelling Strategy</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#multivariate-analysis" id="toc-multivariate-analysis" class="nav-link" data-scroll-target="#multivariate-analysis">Multivariate Analysis</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#mothers" id="toc-mothers" class="nav-link" data-scroll-target="#mothers">Mothers</a></li>
  <li><a href="#fathers" id="toc-fathers" class="nav-link" data-scroll-target="#fathers">Fathers</a></li>
  <li><a href="#role-of-control-variables" id="toc-role-of-control-variables" class="nav-link" data-scroll-target="#role-of-control-variables">Role of control variables</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion-and-conclusion" id="toc-discussion-and-conclusion" class="nav-link" data-scroll-target="#discussion-and-conclusion">Discussion And Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Childcare sharing and parental well-being</h1>
<p class="subtitle lead">A time diary perspective</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Pierre Walthéry &amp; Heejung Chung </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">7/07/2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>The division of childcare between mothers and fathers has traditionally been studied in relation to the parental relationship and children’s subjective well-being (SWB). However, its direct impact on parental SWB remains underexplored. This gap may stem from limitations in existing research on fathers’ involvement, including a lack of differentiation between types of childcare, reliance on simplified time-use measures, and the predominance of cognitive instruments (e.g., life satisfaction) to assess SWB - measures that are less responsive to day-to-day fluctuations. Using data from the 2015 UK Time Use Survey for a subsample of dual-earning households, this study models the relationship between the specific share of various types of childcare performed by fathers and the daily enjoyment levels of parents, a more immediate and affective indicator of SWB. Control variables included the day of the week (weekdays vs.&nbsp;weekends) and the total time fathers spend on childcare. The findings reveal an asymmetric pattern: mothers reported increased daily enjoyment when fathers assumed a moderate share of childcare, while fathers experienced higher levels of enjoyment only when their involvement was more substantial. Both maternal and paternal SWB were also influenced by the total amount of time parents dedicated to childcare. These results underscore the importance of both the distribution and intensity of childcare in shaping parental well-being.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In recent years, policymakers have renewed their focus on how caregiving responsibilities are divided between men and women in heterosexual families, and how these roles might be rebalanced. One of the key motivations for this interest is the impact these divisions have in the perpetuation of the the gender wage gap, which is underpinned by the unequal distribution of unpaid labour (<span class="citation" data-cites="GEO2019">Government Equalities Office (<a href="#ref-GEO2019" role="doc-biblioref">2019</a>)</span>). The enduring notion of the “second shift”—where women continue to shoulder most domestic and caregiving responsibilities—limits their ability to compete on equal terms with men in the labour market (<span class="citation" data-cites="Hochschild1989">Hochschild (<a href="#ref-Hochschild1989" role="doc-biblioref">1989</a>)</span>).</p>
<p>While fathers are spending more time with their children than in previous generations (<span class="citation" data-cites="Craig2014">Craig, Powell, and Smyth (<a href="#ref-Craig2014" role="doc-biblioref">2014</a>)</span>; <span class="citation" data-cites="Gracia2015">Gracia and Esping-Andersen (<a href="#ref-Gracia2015" role="doc-biblioref">2015</a>)</span>) - a trend amplified by the COVID-19 pandemic—substantial gender disparities in childcare persist, particularly during a child’s early years (<span class="citation" data-cites="Fatherhood2016">Fatherhood Institute (<a href="#ref-Fatherhood2016" role="doc-biblioref">2016</a>)</span>; <span class="citation" data-cites="ONS2020">ONS (<a href="#ref-ONS2020" role="doc-biblioref">2020</a>)</span>). At the same time, an increasing number of fathers, especially younger ones, express a desire to be more actively involved in caregiving, even at the expense of their earnings (<span class="citation" data-cites="Working2017">Working Families (<a href="#ref-Working2017" role="doc-biblioref">2017</a>)</span>; <span class="citation" data-cites="Burgess2021">Burgess and Goldman (<a href="#ref-Burgess2021" role="doc-biblioref">2021</a>)</span>).</p>
<p>Nonetheless, entrenched gender norms continue to cast men as breadwinners and women as primary caregivers (<span class="citation" data-cites="Scott2013">Scott (<a href="#ref-Scott2013" role="doc-biblioref">2013</a>)</span>; <span class="citation" data-cites="Taylor2018">Taylor (<a href="#ref-Taylor2018" role="doc-biblioref">2018</a>)</span>). Many fathers remain hesitant to increase their caregiving role due to concerns about potential negative impacts on their careers (<span class="citation" data-cites="Kelland2022">Kelland, Lewis, and Fisher (<a href="#ref-Kelland2022" role="doc-biblioref">2022</a>)</span>; <span class="citation" data-cites="Rudman2013">Rudman and Mescher (<a href="#ref-Rudman2013" role="doc-biblioref">2013</a>)</span>). Similarly, women’s engagement in paid work is still shaped by traditional beliefs, such as the perception that maternal employment negatively affects young children and family life (<span class="citation" data-cites="Scott2013">Scott (<a href="#ref-Scott2013" role="doc-biblioref">2013</a>)</span>). To challenge such deeply held norms, it is essential to scrutinise perceptions of paternal involvement in childcare and its consequences.</p>
<p>A growing body of research has begun to do so by examining the benefits of father involvement in childcare for both children and the parental relationship ( <span class="citation" data-cites="Allen2007a">Allen and Daly (<a href="#ref-Allen2007a" role="doc-biblioref">2007</a>)</span>; <span class="citation" data-cites="Chung2021">Chung (<a href="#ref-Chung2021" role="doc-biblioref">2021</a>)</span>; <span class="citation" data-cites="Norman2018">Norman, Elliot, and Fagan (<a href="#ref-Norman2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="Schober2012">Schober (<a href="#ref-Schober2012" role="doc-biblioref">2012</a>)</span>, <span class="citation" data-cites="Schober2013">Schober (<a href="#ref-Schober2013" role="doc-biblioref">2013</a>)</span>). However, many of these studies focus narrowly on specific caregiving tasks, often linked to the child’s age (e.g., <span class="citation" data-cites="Huerta2014">Huerta et al. (<a href="#ref-Huerta2014" role="doc-biblioref">2014</a>)</span>; <span class="citation" data-cites="Kroll2016">Kroll et al. (<a href="#ref-Kroll2016" role="doc-biblioref">2016</a>)</span>; <span class="citation" data-cites="Nomaguchi2017">K. Nomaguchi, Brown, and Leyman (<a href="#ref-Nomaguchi2017" role="doc-biblioref">2017</a>)</span>; <span class="citation" data-cites="Norman2018">Norman, Elliot, and Fagan (<a href="#ref-Norman2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="Twamley2013">Twamley et al. (<a href="#ref-Twamley2013" role="doc-biblioref">2013</a>)</span>). Such approaches not only overlook the actual amount of time fathers spend on childcare, but also how it is shared between parents.</p>
<p>Even among studies that use moer fine-grained time-use data (e.g. <span class="citation" data-cites="Baxter2011">Baxter and Smart (<a href="#ref-Baxter2011" role="doc-biblioref">2011</a>)</span>), few distinguish between categories of care such as routine vs.&nbsp;non-routine, or solo vs.&nbsp;joint caregiving. Yet these distinctions are crucial for identifying the conditions under which fathers take on a primary caregiving role - an essential contribution for supporting maternal labour market participation.</p>
<p>Furthermore, while some studies have explored the implications of childcare arrangements for parental well-being, most rely on cognitive measures such as life satisfaction (e.g. <span class="citation" data-cites="Glass2016">Glass, Andersson, and Simon (<a href="#ref-Glass2016" role="doc-biblioref">2016</a>)</span>; <span class="citation" data-cites="Schober2016">Schober and Stahl (<a href="#ref-Schober2016" role="doc-biblioref">2016</a>)</span>) , which may not capture short- or medium-term fluctuations due to day-to-day variation in caregiving demands. Much of this research also focuses on negative outcomes - relationship strain, stress, or poor well-being (e.g. <span class="citation" data-cites="Frisco2003">Frisco and Williams (<a href="#ref-Frisco2003" role="doc-biblioref">2003</a>)</span>; <span class="citation" data-cites="Milkie2002">Milkie et al. (<a href="#ref-Milkie2002" role="doc-biblioref">2002</a>)</span>; <span class="citation" data-cites="Nomaguchi2017">K. Nomaguchi, Brown, and Leyman (<a href="#ref-Nomaguchi2017" role="doc-biblioref">2017</a>)</span>; <span class="citation" data-cites="Norman2018">Norman, Elliot, and Fagan (<a href="#ref-Norman2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="Ruppanner2018">Ruppanner, Brandén, and Turunen (<a href="#ref-Ruppanner2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="Schober2012">Schober (<a href="#ref-Schober2012" role="doc-biblioref">2012</a>)</span>; <span class="citation" data-cites="Schober2013">Schober (<a href="#ref-Schober2013" role="doc-biblioref">2013</a>)</span>) - rather than investigating the broader, mutual effects of caregiving on parents’ subjective well-being.</p>
<p>This study addresses these gaps by examining how the time fathers spend on childcare is associated with short-term fluctuations in parental well-being. We do so using an innovative measure - daily enjoyment—from time-diaries collected in the 2015 UK Time Use Survey. Our analysis focuses on how different types of childcare are distributed and experienced, particularly distinguishing between solo and joint care, and routine vs.&nbsp;enrichment activities.</p>
</section>
<section id="background" class="level1">
<h1>Background</h1>
<section id="typologies-of-care" class="level2">
<h2 class="anchored" data-anchor-id="typologies-of-care">Typologies Of Care</h2>
<p>Craig and Mullan (2011) have argued that measuring total caregiving time alone is insufficient to understand the gendered dynamics of childcare, making the case that it is essential to distinguish between types of care and caregiving contexts. Additionally, childcare can occur as a primary or secondary activity, such as while performing housework or paid work, and both forms must be considered (<span class="citation" data-cites="Craig2011">Craig and Powell (<a href="#ref-Craig2011" role="doc-biblioref">2011</a>)</span>).</p>
<p>Research consistently shows that mothers perform more childcare overall and are more likely to be responsible for routine care, whereas fathers tend to engage more in non-routine or enrichment activities (<span class="citation" data-cites="Craig2006">Craig (<a href="#ref-Craig2006" role="doc-biblioref">2006</a>)</span>; <span class="citation" data-cites="Craig2011">Craig and Powell (<a href="#ref-Craig2011" role="doc-biblioref">2011</a>)</span>; <span class="citation" data-cites="Craig2011a">Craig and Mullan (<a href="#ref-Craig2011a" role="doc-biblioref">2011</a>)</span>). Routine care includes physical and scheduled activities such as feeding, bathing, bedtime routines, and school drop-offs, which often conflict with rigid work hours. Non-routine care involves play, reading, and educational activities that tend to fit more flexibly into daily schedules. This division has gendered implications, as it is only when fathers take on a significant share of routine care that mothers can be relieved of the time pressures that constrain their participation in paid employment (Chung &amp; van der Horst, 2018).</p>
<p>In this study, we focus on childcare carried out by a parent alone. Joint caregiving does not free the other parent to engage in alternative activities, and research suggests that in such settings, mothers often retain primary responsibility (Craig 2006). As such, the mental and emotional burden—or “mental load” - continues to fall disproportionately on mothers, even in the context of shared tasks (see also <span class="citation" data-cites="Walzer1996">Walzer (<a href="#ref-Walzer1996" role="doc-biblioref">1996</a>)</span>).</p>
</section>
<section id="shared-care-and-parental-subjective-well-being" class="level2">
<h2 class="anchored" data-anchor-id="shared-care-and-parental-subjective-well-being">Shared care and parental subjective well-being</h2>
<p>Commonly defined as “a broad category of phenomena that includes people’s emotional responses, domain satisfactions, and global judgments of life satisfaction” (<span class="citation" data-cites="Diener1999">Diener et al. (<a href="#ref-Diener1999" role="doc-biblioref">1999</a>)</span>: 277), Subjective Well Being (SWB) is often associated with socially desirable outcomes, be it job- or health related (<span class="citation" data-cites="Lyubomirsky2005">Lyubomirsky, King, and Diener (<a href="#ref-Lyubomirsky2005" role="doc-biblioref">2005</a>)</span>; <span class="citation" data-cites="Pressman2005">Pressman and Cohen (<a href="#ref-Pressman2005" role="doc-biblioref">2005</a>)</span>). . While cognitive dimensions like life satisfaction are widely studied, affective measures of SWB - such as daily mood or enjoyment - remain underexplored, partly due to limited availability in large-scale surveys.</p>
<p>Nonetheless, existing research links unequal divisions of childcare to lower relationship satisfaction and higher rates of marital dissolution (<span class="citation" data-cites="Carlson2016">Carlson, Hanson, and Fitzroy (<a href="#ref-Carlson2016" role="doc-biblioref">2016</a>)</span>; <span class="citation" data-cites="Kalmijn1999">Kalmijn (<a href="#ref-Kalmijn1999" role="doc-biblioref">1999</a>)</span>; <span class="citation" data-cites="Norman2018">Norman, Elliot, and Fagan (<a href="#ref-Norman2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="Schober2012">Schober (<a href="#ref-Schober2012" role="doc-biblioref">2012</a>)</span>). The disproportionate burden of childcare and housework on mothers—particularly those who are employed - has been associated with higher stress and lower well-being (<span class="citation" data-cites="Chandola2019">Chandola et al. (<a href="#ref-Chandola2019" role="doc-biblioref">2019</a>)</span>; <span class="citation" data-cites="Ruppanner2018">Ruppanner, Brandén, and Turunen (<a href="#ref-Ruppanner2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="Taylor2018">Taylor (<a href="#ref-Taylor2018" role="doc-biblioref">2018</a>)</span>).</p>
<p>Ruppanner et al.&nbsp;(2018) find that both parents experience increased time pressure after having children, but the effect is stronger for mothers, especially those with two or more children. Reducing women’s time burden through more equitable caregiving can therefore alleviate stress and improve well-being. Notably, cross-national studies show that parenthood is less negatively associated with happiness in countries offering strong support for families (<span class="citation" data-cites="Glass2016">Glass, Andersson, and Simon (<a href="#ref-Glass2016" role="doc-biblioref">2016</a>)</span>), and that expanding access to formal childcare is linked to greater maternal satisfaction, at least in Germany (Schober &amp; Stahl, 2016).</p>
<p>While parenthood is often associated with stress and lower life satisfaction, it also offers emotional rewards. Research using American Time Use Survey data has shown that parents report greater happiness during activities involving the presence of children, compared to non-parents (<span class="citation" data-cites="Negraia2020">Negraia and Augustine (<a href="#ref-Negraia2020" role="doc-biblioref">2020</a>)</span>). This may be particularly true for fathers, for whom caregiving can foster a sense of purpose and recognition (<span class="citation" data-cites="Nomaguchi2003">K. M. Nomaguchi and Milkie (<a href="#ref-Nomaguchi2003" role="doc-biblioref">2003</a>)</span>). Involved fathers also report higher job satisfaction, better work-family balance, and lower work-family conflict (<span class="citation" data-cites="Ladge2015">Ladge et al. (<a href="#ref-Ladge2015" role="doc-biblioref">2015</a>)</span>).</p>
<p>Enrichment activities—typically play-based and stimulating—tend to be the most enjoyable type of childcare, especially for fathers (<span class="citation" data-cites="Craig2014">Craig, Powell, and Smyth (<a href="#ref-Craig2014" role="doc-biblioref">2014</a>)</span>). These activities align more closely with emerging representations of nurturing masculinity (<span class="citation" data-cites="Brandth1998">Brandth and Kvande (<a href="#ref-Brandth1998" role="doc-biblioref">1998</a>)</span>). In contrast, fathers’ engagement in routine caregiving may not yield the same emotional benefits and may still be perceived as a “feminine” responsibility.</p>
<p>For mothers, however, any increase in fathers’ involvement - especially in routine tasks—may have a stronger positive impact. A more equitable sharing of childcare responsibilities can reduce the time pressure and stress they experience, contributing to improved well-being (<span class="citation" data-cites="Nomaguchi2017">K. Nomaguchi, Brown, and Leyman (<a href="#ref-Nomaguchi2017" role="doc-biblioref">2017</a>)</span>; <span class="citation" data-cites="Chandola2019">Chandola et al. (<a href="#ref-Chandola2019" role="doc-biblioref">2019</a>)</span>).</p>
</section>
<section id="summary-and-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="summary-and-hypotheses">Summary And Hypotheses</h2>
<p>Our overall hypothesis is that the greater the share of childcare taken on by fathers, the larger the improvement in well-being for mothers and fathers, particularly daily enjoyment. We would expect that a more balanced sharing of childcare, especially routine childcare, would improve maternal well-being by reducing their time-pressure and stress levels. We expect father’s well-being and enjoyment levels to increase as they are able to spend more time doing childcare, and taking on a larger role, especially in enrichment/non-routine childcare.</p>
</section>
</section>
<section id="data-and-methods" class="level1">
<h1>Data And Methods</h1>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>This study draws on the 2015 UK Time Use Survey (TUS), a two-stage stratified random sample survey representative of non-institutional households across the UK. Data were collected through self-completed time diaries—coded using the HETUS classification—and face-to-face individual questionnaires. Diaries recorded primary and secondary activities in 10-minute intervals over two 24-hour periods (one weekday and one weekend day). Respondents also documented the location of activities, co-presence with others, and their level of enjoyment. Diary days were randomly assigned throughout the year and were the same for all members of the same household.</p>
<p>The overall sample includes 11,421 individuals from 4,733 households, of which 8,210 individuals across 3,606 households completed both time diaries.</p>
</section>
<section id="sample" class="level2">
<h2 class="anchored" data-anchor-id="sample">Sample</h2>
<p>The analytical sample focuses on diary days in 2014–2015 from UK households comprising two cohabiting heterosexual adults, both in paid employment, with at least one child aged 0–14. At least one parent must have reported childcare activities in their diary. The analysis is conducted at the household level using matched data for mothers and fathers. Single-parent households and multi-family or multigenerational households were excluded to minimise confounding by non-parental caregiving.</p>
<p>The resulting analytic sample includes 852 valid diary days from 428 households with complete information on childcare and well-being. While the relatively small sample size limits statistical power for multivariate analysis, it remains a valid representative sample from which inferences to the days of UK households can be made, albeit with caution.</p>
</section>
<section id="dependent-variables" class="level2">
<h2 class="anchored" data-anchor-id="dependent-variables">Dependent Variables</h2>
<ul>
<li><p><em>Overall daily enjoyment</em> This measure of experienced well-being was recorded in the time-diary using a 7-point scale. We operationalised it as the average enjoyment score across all non-resting activities for a full day. We chose to focus on overall daily enjoyment rather than enjoyment disaggregated by care type due to sample size constraints. As this measure was only introduced in October 2014 after fieldwork had already started, approximately 25% of cases lack enjoyment data.</p></li>
<li><p><em>Evaluative well-being and life satisfaction</em> In order for our results to remain comparable with other studies, we also used more traditional measures of cognitive well-being:</p>
<ul>
<li>Life Satisfaction: “Overall, how satisfied are you with your life nowadays?” (0 = Not at all, 10 = Completely). Due to a mid-fieldwork change in the scale (from 7 to 10 points), we standardised and merged both versions to maximise sample size;</li>
<li>Work-Life Balance Satisfaction: “How dissatisfied or satisfied are you with your work-life/work-family balance?” (1–7 scale);</li>
<li>Social Life Satisfaction: “How dissatisfied or satisfied are you with your social life?” (1–7 scale).</li>
</ul></li>
</ul>
<p>These facets are particularly relevant to parenting and caregiving contexts.</p>
</section>
<section id="independent-variables" class="level2">
<h2 class="anchored" data-anchor-id="independent-variables">Independent variables</h2>
<p><em>Fathers’ share of childcare</em> The main explanatory variable captures the percentage of total childcare time (across both parents) provided by fathers on a given day. We distinguish between:</p>
<ul>
<li>Routine Care: Feeding, bathing, dressing, soothing, transport to/from school.</li>
<li>Enrichment/Non-Routine Care: Talking, reading, playing, storytelling, educational engagement as proposed by <span class="citation" data-cites="Craig2011">Craig and Powell (<a href="#ref-Craig2011" role="doc-biblioref">2011</a>)</span></li>
<li>Solo Care: Provided when the other parent is not present.</li>
<li>Primary Care: Recorded as the main activity, regardless of secondary activities.</li>
</ul>
<p>For each type, we calculated the father’s minutes spent on caregiving as a share of the total caregiving minutes within the household. To capture potential non-linear effects, we created an ordinal variable with three categories:</p>
<ol type="1">
<li>Fathers performed no childcare (reference group)</li>
<li>Fathers performed &lt;40% of total care</li>
<li>Fathers performed ≥40% of total care</li>
</ol>
<p>We chose a 40% threshold instead of 50% to increase the number of observations in the upper category, given the low prevalence of fathers taking on the majority of care. Table 1 provides a description of these different types in our data. Solo care was defined as care provided the parent when the other parent was not present at the same time.</p>
<div id="tab-1">
<table class="caption-top table">
<caption>Table 1. Categories of care</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 20%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Concept</th>
<th>Activities involved*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nature of care</td>
<td>Routine</td>
<td>Feeding, bathing, dressing, putting to bed, carrying, soothing, transport to school</td>
</tr>
<tr class="even">
<td>-</td>
<td>Enrichment/non routine care</td>
<td>Talking, listening, teaching, helping children learn, reading, telling stories, and playing games etc..</td>
</tr>
<tr class="odd">
<td>Involvement of the other parent</td>
<td>Solo care</td>
<td>When care is provided without the other parent involved</td>
</tr>
<tr class="even">
<td>Primacy of care</td>
<td>Primary</td>
<td>Any childcare provided as the main activity by the parent, with or without other recorded activities</td>
</tr>
</tbody>
</table>
<pre><code>* as primary or secondary activities</code></pre>
</div>
<p>For each one of these types, the number of minutes fathers spent caring was divided by the total caring time spent by mothers and fathers within each household then multiplied by 100. In order to account for the likely nonlinear effect of this variable on well-being, we derived a three-category ordinal version consisting of: fathers not doing any childcare on diary day (reference category); fathers taking on less than 40% of the childcare; fathers taking on 40% or more of the childcare. The cutting point was set at 40 % rather than 50% in order to alleviate the small number of fathers caring more than 50% of the time.</p>
</section>
<section id="modelling-strategy" class="level2">
<h2 class="anchored" data-anchor-id="modelling-strategy">Modelling Strategy</h2>
<p>We examined both bivariate and multivariate associations between paternal share of childcare and parental well-being outcomes, broken down by type of care. As each respondent contributed two diary days, we estimated OLS regressions with robust standard errors using the estimatr package in R (<span class="citation" data-cites="Blair2024">Blair et al. (<a href="#ref-Blair2024" role="doc-biblioref">2024</a>)</span>).</p>
<p>We controlled for the socio-demographic characteristics of respondents, as they are known to influence the time spent on childcare (<span class="citation" data-cites="Craig2011">Craig and Powell (<a href="#ref-Craig2011" role="doc-biblioref">2011</a>)</span>) and well-being (<span class="citation" data-cites="Kroll2016">Kroll et al. (<a href="#ref-Kroll2016" role="doc-biblioref">2016</a>)</span>; <span class="citation" data-cites="Milkie2002">Milkie et al. (<a href="#ref-Milkie2002" role="doc-biblioref">2002</a>)</span>; <span class="citation" data-cites="Schober2012">Schober (<a href="#ref-Schober2012" role="doc-biblioref">2012</a>)</span>). Control variables included:</p>
<ul>
<li>Parental education</li>
<li>Household employment configuration (dual full-time, one full-/one part-time)</li>
<li>Age of each parent</li>
<li>Day type (weekday vs weekend)</li>
<li>Fathers’ absolute time spent on childcare (to separate the effect of sharing from quantity of care)</li>
</ul>
<p>We included this last control to account for the possibility that the effect of care share may differ depending on whether a day involved high or low caregiving demands for the mother.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>On average, the respondents in our sample tend to be more educated than the general population, with mothers more highly educated than fathers. This discrepancy is likely explained by the higher educational attainment among employed mothers compared to those who are economically inactive. Notably, and perhaps unsurprisingly, there is a gendered divide in access to flexible working arrangements: 31.1% of households have mothers working under some form of flexible hours (18.1% full-time and 13% part-time), compared to only 12.7% of fathers (7.6% full-time and 5.1% part-time). In 35.2% of households, mothers served as secondary earners while fathers worked full-time, compared to 46.2% of households where both parents were in full-time employment. Finally, 81% of households had at least one child below primary school age—unsurprising given the study’s design, which required at least one episode of childcare to be recorded in the diary. Consequently, households with children over the age of 10 were rare.</p>
<div class="cell">
<div class="cell-output-display">
<table class="gmisc_table caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th colspan="5" style="text-align: left;">Table 2: Sample characteristics</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; border-bottom: 1px solid grey; border-top: 2px solid grey;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">Mothers %</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">N(mothers)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">Fathers %</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">N(fathers)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Degree</td>
<td style="text-align: center;">48.2</td>
<td style="text-align: center;">203</td>
<td style="text-align: center;">38.1</td>
<td style="text-align: center;">143</td>
</tr>
<tr class="even">
<td style="text-align: left;">Higher education</td>
<td style="text-align: center;">10.8</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">13.2</td>
<td style="text-align: center;">56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Secondary or below</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">177</td>
<td style="text-align: center;">48.7</td>
<td style="text-align: center;">218</td>
</tr>
<tr class="even">
<td style="text-align: left;">FT-No Flexible WT</td>
<td style="text-align: center;">33.2</td>
<td style="text-align: center;">138</td>
<td style="text-align: center;">7.6</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FT+Flexible WT</td>
<td style="text-align: center;">12.9</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">51.9</td>
<td style="text-align: center;">227</td>
</tr>
<tr class="even">
<td style="text-align: left;">PT-No Flexible WT</td>
<td style="text-align: center;">17.1</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">32.6</td>
<td style="text-align: center;">138</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PT+Flexible WT</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">82</td>
<td style="text-align: center;">5.1</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: center;">34.4</td>
<td style="text-align: center;">426</td>
<td style="text-align: center;">36.8</td>
<td style="text-align: center;">426</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dual earner</td>
<td style="text-align: center;">25.5</td>
<td style="text-align: center;">109</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Full-time F/Part-time M</td>
<td style="text-align: center;">24.1</td>
<td style="text-align: center;">103</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">153</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Youngest child is 0-4</td>
<td style="text-align: center;">80.7</td>
<td style="text-align: center;">339</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Youngest child is 5-10</td>
<td style="text-align: center;">19.3</td>
<td style="text-align: center;">89</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left; border-bottom: 2px solid grey;">Youngest child is 11-15</td>
<td style="text-align: center; border-bottom: 2px solid grey;"></td>
<td style="text-align: center; border-bottom: 2px solid grey;"></td>
<td style="text-align: center; border-bottom: 2px solid grey;">-</td>
<td style="text-align: center; border-bottom: 2px solid grey;">-</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="5" style="text-align: left;">Socio demographic characteristics of the matched household sample N=852 days,428 mothers and fathers. Data: UK TUS 2015. * M=Mother F=Father FT= Full-time</td>
</tr>
</tfoot>

</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="gmisc_table caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th colspan="7" style="text-align: left;">Table 3: sharing of childcare between mothers and fathers</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; border-bottom: 1px solid grey; border-top: 2px solid grey;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">Not caring</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">&lt;40%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">&gt;=40%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">Not caring</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">&lt;40%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">&gt;=40%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Primary caring</td>
<td style="text-align: center;">29.6</td>
<td style="text-align: center;">35.3</td>
<td style="text-align: center;">35.1</td>
<td style="text-align: center;">115</td>
<td style="text-align: center;">146</td>
<td style="text-align: center;">146</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sole caring</td>
<td style="text-align: center;">52.7</td>
<td style="text-align: center;">20.4</td>
<td style="text-align: center;">26.9</td>
<td style="text-align: center;">179</td>
<td style="text-align: center;">87</td>
<td style="text-align: center;">99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Routine caring</td>
<td style="text-align: center;">35.1</td>
<td style="text-align: center;">37.5</td>
<td style="text-align: center;">27.4</td>
<td style="text-align: center;">125</td>
<td style="text-align: center;">165</td>
<td style="text-align: center;">117</td>
</tr>
<tr class="even">
<td style="text-align: left; border-bottom: 2px solid grey;">Enriched caring</td>
<td style="text-align: center; border-bottom: 2px solid grey;">36.6</td>
<td style="text-align: center; border-bottom: 2px solid grey;">26.6</td>
<td style="text-align: center; border-bottom: 2px solid grey;">36.7</td>
<td style="text-align: center; border-bottom: 2px solid grey;">122</td>
<td style="text-align: center; border-bottom: 2px solid grey;">90</td>
<td style="text-align: center; border-bottom: 2px solid grey;">125</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="7" style="text-align: left;">Three category proportion of the total caring time spent in the household carried out by fathers, by type of caring. N=852 days, 428 households. Data: UK TUS 2015</td>
</tr>
</tfoot>

</table>
</div>
</div>
<p>Table 3 provides an initial overview of how childcare responsibilities were distributed between mothers and fathers. In 29.7% of cases, fathers did not report participating in any form of childcare on the diary day. However, 70.4% reported engaging in primary childcare, with roughly one-third taking on 40% or more of the total care. Interestingly, 62% of fathers participated in both routine and enriched care activities - a pattern likely influenced by the dual-earner composition of the sample, characterised by higher levels of qualification than the general population, which tends to correlate with higher levels of paternal involvement in childcare overall (see also <span class="citation" data-cites="Dotti2016">Dotti Sani and Treas (<a href="#ref-Dotti2016" role="doc-biblioref">2016</a>)</span>).</p>
<p>As expected, no category of childcare showed a majority of fathers taking on more time than mothers. The proportion of fathers reporting at least 40% of total childcare time ranged from 20.3% for solo care to 36% for joint care. Fathers were slightly more likely to provide 40% or more of enriched and solo care (36.8% and 26.9%, respectively) compared to providing less than 40% (26.5% and 20.3%, respectively). These patterns varied depending on whether the diary was recorded on a weekday or weekend. For instance, 25.4% of fathers reported no childcare on weekdays, compared to 18.6% on weekends (data not shown).</p>
<div class="cell">
<div class="cell-output-display">
<table class="gmisc_table caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" style="text-align: left;">Table 4. Mean immediate and evaluative well-being</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; border-bottom: 1px solid grey; border-top: 2px solid grey;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">Mothers</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">N(mothers)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">Fathers</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: 900; border-bottom: 1px solid grey; border-top: 2px solid grey;">N(fathers)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean daily enjoyment</td>
<td style="text-align: center;">5.8</td>
<td style="text-align: center;">178</td>
<td style="text-align: center;">5.6</td>
<td style="text-align: center;">188</td>
</tr>
<tr class="even">
<td style="text-align: left;">Life satisfaction</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">149</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work-life balance satisfaction</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">392</td>
<td style="text-align: center;">4.7</td>
<td style="text-align: center;">283</td>
</tr>
<tr class="even">
<td style="text-align: left; border-bottom: 2px solid grey;">Satisfaction with social life</td>
<td style="text-align: center; border-bottom: 2px solid grey;">4.8</td>
<td style="text-align: center; border-bottom: 2px solid grey;">396</td>
<td style="text-align: center; border-bottom: 2px solid grey;">4.7</td>
<td style="text-align: center; border-bottom: 2px solid grey;">284</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="5" style="text-align: left;">Mean value of well-being outcomes for mothers and fathers in the<br>
matched household sample N=852 days, 428 households. Data: UK TUS 2015. Outcomes range from 1 to 7, except for life satisfaction for which scores were standardized.</td>
</tr>
</tfoot>

</table>
</div>
</div>
<p>Table 4 summarizes the well-being outcomes for mothers and fathers, including daily enjoyment, life satisfaction, partner satisfaction, and satisfaction with work-life balance. While means were generally similar across genders, mothers consistently reported slightly higher scores. The number of diary entries was higher for mothers than fathers, except in the case of daily enjoyment.</p>
<section id="multivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-analysis">Multivariate Analysis</h2>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview">Overview</h3>
<p>Initial analyses revealed no significant positive association between either mothers’ or fathers’ well-being and the proportion of childcare undertaken by fathers. In contrast, several negative associations were identified on days when fathers accounted for more than 40% of the total childcare time. Overall, models performed better in predicting daily enjoyment and life satisfaction than social life or work-life balance satisfaction.</p>
<p>The absolute time fathers spent on childcare, rather than their share relative to mothers, was weakly positively associated with their well-being. When interaction terms were introduced - examining how fathers’ share of care intersected with each parent’s total care time - a more nuanced picture emerged, particularly for fathers.</p>
</section>
<section id="mothers" class="level3">
<h3 class="anchored" data-anchor-id="mothers">Mothers</h3>
<p>Table 5 indicates no clear evidence that an increased paternal share of childcare correlates positively with mothers’ well-being, after adjusting for socio-demographic factors and total childcare time. Unexpectedly, maternal daily enjoyment was lower in households where fathers undertook more than 40% of solo care (-.25, <span class="math inline">\(p&lt;.05\)</span>). A similar pattern was observed for life satisfaction when fathers provided 40% or more of primary care (-.40, <span class="math inline">\(p&lt;.05\)</span>). A larger share of solo care by fathers’ also negatively affected mothers’ life satisfaction, although this finding was only significant at the p&lt;.1 level.</p>
<p>Some weakly significant positive associations were identified: for example, fathers’ time spent on primary and routine childcare was positively related to mothers’ life satisfaction (.16 and .12 <span class="math inline">\(p&lt;.1\)</span>, respectively). Prior to controlling for covariates, mothers reported higher daily enjoyment when fathers provided 1–40% of primary childcare (results available upon request), suggesting that moderate paternal involvement may be more beneficial than extensive involvement.</p>
<div class="cell" data-tbl-cap="Table 5 OLS models of mothers' well-being by fathers share of childcare">
<div id="sasjwssdzo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#sasjwssdzo table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#sasjwssdzo thead, #sasjwssdzo tbody, #sasjwssdzo tfoot, #sasjwssdzo tr, #sasjwssdzo td, #sasjwssdzo th {
  border-style: none;
}

#sasjwssdzo p {
  margin: 0;
  padding: 0;
}

#sasjwssdzo .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#sasjwssdzo .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#sasjwssdzo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#sasjwssdzo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#sasjwssdzo .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sasjwssdzo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sasjwssdzo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sasjwssdzo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#sasjwssdzo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#sasjwssdzo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#sasjwssdzo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#sasjwssdzo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#sasjwssdzo .gt_spanner_row {
  border-bottom-style: hidden;
}

#sasjwssdzo .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#sasjwssdzo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#sasjwssdzo .gt_from_md > :first-child {
  margin-top: 0;
}

#sasjwssdzo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#sasjwssdzo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#sasjwssdzo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#sasjwssdzo .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#sasjwssdzo .gt_row_group_first td {
  border-top-width: 2px;
}

#sasjwssdzo .gt_row_group_first th {
  border-top-width: 2px;
}

#sasjwssdzo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sasjwssdzo .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#sasjwssdzo .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#sasjwssdzo .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sasjwssdzo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sasjwssdzo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#sasjwssdzo .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#sasjwssdzo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#sasjwssdzo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sasjwssdzo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sasjwssdzo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#sasjwssdzo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sasjwssdzo .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#sasjwssdzo .gt_left {
  text-align: left;
}

#sasjwssdzo .gt_center {
  text-align: center;
}

#sasjwssdzo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#sasjwssdzo .gt_font_normal {
  font-weight: normal;
}

#sasjwssdzo .gt_font_bold {
  font-weight: bold;
}

#sasjwssdzo .gt_font_italic {
  font-style: italic;
}

#sasjwssdzo .gt_super {
  font-size: 65%;
}

#sasjwssdzo .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#sasjwssdzo .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#sasjwssdzo .gt_indent_1 {
  text-indent: 5px;
}

#sasjwssdzo .gt_indent_2 {
  text-indent: 10px;
}

#sasjwssdzo .gt_indent_3 {
  text-indent: 15px;
}

#sasjwssdzo .gt_indent_4 {
  text-indent: 20px;
}

#sasjwssdzo .gt_indent_5 {
  text-indent: 25px;
}

#sasjwssdzo .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#sasjwssdzo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"><caption><p>Table 5 OLS models of mothers’ well-being by fathers share of
childcare</p></caption>
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="a-"> <span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Primary">Primary<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Alone">Alone<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Routine">Routine<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Enriched">Enriched<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Work-life balance satisfaction">Work-life balance satisfaction</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Intercept</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">4.54***</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">4.49***</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">4.47***</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">4.39***</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.51)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.52)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.50)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.54)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">-0.00</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">-0.08</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.10</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">0.04</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.17)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.17)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.16)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.17)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">-0.20</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">-0.23</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">-0.27</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">0.05</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.21)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.21)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.20)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.19)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">0.15+</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">0.12</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.12</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">0.08</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.08)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.08)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.07)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.08)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">771</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">679</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">763</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">653</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">R2</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">0.013</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">0.014</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.018</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">0.013</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">-0.000</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">-0.001</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.004</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">-0.002</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">AIC</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">2876.4</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">2532.6</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">2841.7</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">2430.4</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Life satisfaction">Life satisfaction</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Life satisfaction   " class="gt_row gt_left">Intercept</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.73+</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.80+</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.60</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">0.40</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.43)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.43)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.41)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.44)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">-0.08</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">-0.03</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.00</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">-0.11</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.14)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.15)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.14)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.12)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">-0.39*</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">-0.40+</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">-0.26</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">0.08</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.20)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.21)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.19)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.15)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.11+</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.10</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.07</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">-0.06</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.06)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.07)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.06)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.07)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">412</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">357</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">409</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">344</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">R2</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.054</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.066</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.044</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">0.045</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.031</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.039</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.019</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">0.017</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">AIC</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">1179.2</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">1034.1</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">1151.5</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">988.7</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Satisfaction with social life">Satisfaction with social life</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Satisfaction with social life   " class="gt_row gt_left">Intercept</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">4.99***</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">4.74***</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">4.88***</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">4.92***</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.53)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.52)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.51)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.55)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">-0.11</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">-0.11</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">-0.10</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">-0.34+</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.16)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.17)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.16)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.18)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.11</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">-0.01</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.06</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">0.13</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.19)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.20)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.18)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.18)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">-0.08</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.01</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.01</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">-0.09</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.08)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.09)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.08)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.07)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">778</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">687</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">771</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">658</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">R2</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.022</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.023</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.019</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">0.047</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.009</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.008</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.006</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">0.032</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">AIC</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">2884.2</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">2566.9</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">2871.5</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">2497.7</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Enjoyment">Enjoyment</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Enjoyment   " class="gt_row gt_left">Intercept</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">6.07***</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">6.11***</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">6.07***</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">6.27***</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.30)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.27)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.28)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.27)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">-0.03</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">-0.00</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">-0.07</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.04</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.10)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.11)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.10)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.09)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">-0.15</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">-0.25*</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">-0.13</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">-0.16</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.13)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.12)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.13)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.11)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.03</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.05</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">-0.03</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.05</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.05)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.05)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.06)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.04)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">373</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">335</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">370</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">331</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">R2</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.057</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.068</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">0.059</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.064</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.031</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.040</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">0.033</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.035</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">AIC</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">831.6</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">738.4</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">808.4</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">685.4</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="5">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Matched household-level dataset of parents aged 16 and above in heterosexual couples with at least one child under 15. data: UK TUS 2015 Coefficients denote the change in the specified well-being scale.</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</section>
<section id="fathers" class="level3">
<h3 class="anchored" data-anchor-id="fathers">Fathers</h3>
<p>Turning to fathers in Table 6, we observed a negative association between life satisfaction and their assuming more than 40% of the primary or solo childcare responsibilities (respectively <span class="math inline">\(-.44\)</span> and <span class="math inline">\(-.43\)</span>, <span class="math inline">\(p&lt;.05\)</span>). Conversely, fathers’ life satisfaction improved with the absolute amount of time spent on primary childcare (<span class="math inline">\(.16, p&lt;.05\)</span>), regardless of their share relative to mothers.</p>
<p>Fathers’ satisfaction with social life was positively associated with taking on a large share of routine care relative to mothers (<span class="math inline">\(.47, p&lt;.05\)</span>). However, this came with a trade-off: the more time fathers spent on routine childcare, the lower their social life satisfaction (<span class="math inline">\(-.14, p&lt;.05\)</span>).</p>
<p>There was a weakly significant indication that fathers who undertook less than 40% of primary care reported higher daily enjoyment (<span class="math inline">\(.23, p&lt;.1\)</span>). Consistent with previous research, time spent on enrichment care was positively associated with daily enjoyment (<span class="math inline">\(.12, p&lt;.05\)</span>).</p>
<div class="cell" data-tbl-cap="Table 6 OLS models of fathers well-being by fathers share of childcare">
<div class="cell-output-display">
<div id="wmtrasjtko" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#wmtrasjtko table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#wmtrasjtko thead, #wmtrasjtko tbody, #wmtrasjtko tfoot, #wmtrasjtko tr, #wmtrasjtko td, #wmtrasjtko th {
  border-style: none;
}

#wmtrasjtko p {
  margin: 0;
  padding: 0;
}

#wmtrasjtko .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wmtrasjtko .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#wmtrasjtko .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wmtrasjtko .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wmtrasjtko .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wmtrasjtko .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wmtrasjtko .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wmtrasjtko .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wmtrasjtko .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wmtrasjtko .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wmtrasjtko .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wmtrasjtko .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wmtrasjtko .gt_spanner_row {
  border-bottom-style: hidden;
}

#wmtrasjtko .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#wmtrasjtko .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wmtrasjtko .gt_from_md > :first-child {
  margin-top: 0;
}

#wmtrasjtko .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wmtrasjtko .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wmtrasjtko .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#wmtrasjtko .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wmtrasjtko .gt_row_group_first td {
  border-top-width: 2px;
}

#wmtrasjtko .gt_row_group_first th {
  border-top-width: 2px;
}

#wmtrasjtko .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wmtrasjtko .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wmtrasjtko .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wmtrasjtko .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wmtrasjtko .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wmtrasjtko .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wmtrasjtko .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#wmtrasjtko .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wmtrasjtko .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wmtrasjtko .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wmtrasjtko .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wmtrasjtko .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wmtrasjtko .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wmtrasjtko .gt_left {
  text-align: left;
}

#wmtrasjtko .gt_center {
  text-align: center;
}

#wmtrasjtko .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wmtrasjtko .gt_font_normal {
  font-weight: normal;
}

#wmtrasjtko .gt_font_bold {
  font-weight: bold;
}

#wmtrasjtko .gt_font_italic {
  font-style: italic;
}

#wmtrasjtko .gt_super {
  font-size: 65%;
}

#wmtrasjtko .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#wmtrasjtko .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wmtrasjtko .gt_indent_1 {
  text-indent: 5px;
}

#wmtrasjtko .gt_indent_2 {
  text-indent: 10px;
}

#wmtrasjtko .gt_indent_3 {
  text-indent: 15px;
}

#wmtrasjtko .gt_indent_4 {
  text-indent: 20px;
}

#wmtrasjtko .gt_indent_5 {
  text-indent: 25px;
}

#wmtrasjtko .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#wmtrasjtko div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"><caption><p>Table 6 OLS models of fathers well-being by fathers share of
childcare</p></caption>
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="a-"> <span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Primary">Primary<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Alone">Alone<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Routine">Routine<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Enriched">Enriched<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Work-life balance satisfaction">Work-life balance satisfaction</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Intercept</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">4.44***</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">4.39***</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">4.34***</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">4.62***</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.57)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.54)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.57)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.56)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">0.11</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">0.16</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.14</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">0.03</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.20)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.19)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.20)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.20)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">0.09</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">0.09</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.23</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">-0.17</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.23)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.20)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.21)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.21)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">-0.05</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">-0.04</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">-0.05</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">-0.02</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left"></td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">(0.08)</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">(0.07)</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">(0.07)</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">(0.08)</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">546</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">487</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">547</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">449</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">R2</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">0.010</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">0.012</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">0.012</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">0.020</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">-0.008</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">-0.009</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">-0.007</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">-0.002</td></tr>
    <tr><td headers="Work-life balance satisfaction   " class="gt_row gt_left">AIC</td>
<td headers="Work-life balance satisfaction  Primary" class="gt_row gt_center">2018.5</td>
<td headers="Work-life balance satisfaction  Alone" class="gt_row gt_center">1792.2</td>
<td headers="Work-life balance satisfaction  Routine" class="gt_row gt_center">2017.6</td>
<td headers="Work-life balance satisfaction  Enriched" class="gt_row gt_center">1653.5</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Life satisfaction">Life satisfaction</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Life satisfaction   " class="gt_row gt_left">Intercept</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">-0.22</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.04</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">-0.40</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">-0.18</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.54)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.55)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.52)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.53)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.04</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">-0.16</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.14</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">-0.05</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.17)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.21)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.18)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.15)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">-0.44*</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">-0.43*</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.01</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">-0.24</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.21)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.20)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.22)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.17)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.16*</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.08</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">-0.03</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">0.10</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left"></td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">(0.07)</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">(0.10)</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">(0.07)</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">(0.08)</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">290</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">256</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">292</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">242</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">R2</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.049</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">0.035</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">0.020</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">0.040</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">0.015</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">-0.005</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">-0.015</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">-0.002</td></tr>
    <tr><td headers="Life satisfaction   " class="gt_row gt_left">AIC</td>
<td headers="Life satisfaction  Primary" class="gt_row gt_center">897.4</td>
<td headers="Life satisfaction  Alone" class="gt_row gt_center">789.8</td>
<td headers="Life satisfaction  Routine" class="gt_row gt_center">884.7</td>
<td headers="Life satisfaction  Enriched" class="gt_row gt_center">741.5</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Satisfaction with social life">Satisfaction with social life</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Satisfaction with social life   " class="gt_row gt_left">Intercept</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">4.23***</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">4.49***</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">4.24***</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">4.63***</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.54)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.58)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.56)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.56)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.33</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.04</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.23</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">-0.05</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.21)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.19)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.21)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.21)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.35</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.16</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.47*</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">-0.13</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.24)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.20)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.23)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.25)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">-0.13</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">-0.10</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">-0.14*</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">-0.06</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left"></td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">(0.09)</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">(0.07)</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">(0.07)</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">(0.10)</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">548</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">488</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">548</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">451</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">R2</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.027</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.027</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.029</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">0.023</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">0.008</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">0.007</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">0.011</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">0.001</td></tr>
    <tr><td headers="Satisfaction with social life   " class="gt_row gt_left">AIC</td>
<td headers="Satisfaction with social life  Primary" class="gt_row gt_center">2036.0</td>
<td headers="Satisfaction with social life  Alone" class="gt_row gt_center">1834.0</td>
<td headers="Satisfaction with social life  Routine" class="gt_row gt_center">2030.2</td>
<td headers="Satisfaction with social life  Enriched" class="gt_row gt_center">1670.1</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="5" class="gt_group_heading" scope="colgroup" id="Enjoyment">Enjoyment</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Enjoyment   " class="gt_row gt_left">Intercept</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">5.67***</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">5.94***</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">5.75***</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">6.13***</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.26)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.28)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.26)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.29)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Paternal share &lt;40% (ref. 0%)</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.23+</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">-0.11</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">0.14</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">-0.05</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.12)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.13)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.11)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.12)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Paternal share &gt;=40%</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.19</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.07</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">0.18</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">-0.05</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.13)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.12)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.12)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.13)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Time spent on childcare</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.03</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.01</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">-0.03</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.12*</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left"></td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">(0.05)</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">(0.06)</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">(0.05)</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">(0.05)</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">Num.Obs.</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">387</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">346</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">384</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">331</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">R2</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.139</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.121</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">0.122</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.142</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">R2 Adj.</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">0.116</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">0.095</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">0.098</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">0.115</td></tr>
    <tr><td headers="Enjoyment   " class="gt_row gt_left">AIC</td>
<td headers="Enjoyment  Primary" class="gt_row gt_center">949.0</td>
<td headers="Enjoyment  Alone" class="gt_row gt_center">846.5</td>
<td headers="Enjoyment  Routine" class="gt_row gt_center">919.4</td>
<td headers="Enjoyment  Enriched" class="gt_row gt_center">730.1</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="5">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Matched household-level dataset of parents aged 16 and above in heterosexual couples with at least one child under 15. data: UK TUS 2015 Coefficients denote the change in the specified well-being scale.</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<p>Interaction effects - between the amount of time spent on childcare by each parent and the share taken on by fathers and their impact on the daily enjoyment of parents - were also explored (see Tables 7 and 8). For mothers, no significant interactions were found (Table 7). Among fathers, however, a positive interaction was identified: those who both spent significant time on and undertook a large share (&gt;40%) of primary childcare reported greater daily enjoyment (.16, p&lt;.05). In contrast, for routine care, higher time investment was associated with lower enjoyment if the father’s share was moderate, echoing above findings (<span class="math inline">\(-.21,p&lt;.05\)</span>).</p>
<div class="cell tbl-cap-location-top" data-tbl-cap="Table 7 Interactions between duration and sharing of childcare, daily enjoyment of mothers">
<div class="cell-output-display">
<div id="innakzbltt" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#innakzbltt table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#innakzbltt thead, #innakzbltt tbody, #innakzbltt tfoot, #innakzbltt tr, #innakzbltt td, #innakzbltt th {
  border-style: none;
}

#innakzbltt p {
  margin: 0;
  padding: 0;
}

#innakzbltt .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#innakzbltt .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#innakzbltt .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#innakzbltt .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#innakzbltt .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#innakzbltt .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#innakzbltt .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#innakzbltt .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#innakzbltt .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#innakzbltt .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#innakzbltt .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#innakzbltt .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#innakzbltt .gt_spanner_row {
  border-bottom-style: hidden;
}

#innakzbltt .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#innakzbltt .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#innakzbltt .gt_from_md > :first-child {
  margin-top: 0;
}

#innakzbltt .gt_from_md > :last-child {
  margin-bottom: 0;
}

#innakzbltt .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#innakzbltt .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#innakzbltt .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#innakzbltt .gt_row_group_first td {
  border-top-width: 2px;
}

#innakzbltt .gt_row_group_first th {
  border-top-width: 2px;
}

#innakzbltt .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#innakzbltt .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#innakzbltt .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#innakzbltt .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#innakzbltt .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#innakzbltt .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#innakzbltt .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#innakzbltt .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#innakzbltt .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#innakzbltt .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#innakzbltt .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#innakzbltt .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#innakzbltt .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#innakzbltt .gt_left {
  text-align: left;
}

#innakzbltt .gt_center {
  text-align: center;
}

#innakzbltt .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#innakzbltt .gt_font_normal {
  font-weight: normal;
}

#innakzbltt .gt_font_bold {
  font-weight: bold;
}

#innakzbltt .gt_font_italic {
  font-style: italic;
}

#innakzbltt .gt_super {
  font-size: 65%;
}

#innakzbltt .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#innakzbltt .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#innakzbltt .gt_indent_1 {
  text-indent: 5px;
}

#innakzbltt .gt_indent_2 {
  text-indent: 10px;
}

#innakzbltt .gt_indent_3 {
  text-indent: 15px;
}

#innakzbltt .gt_indent_4 {
  text-indent: 20px;
}

#innakzbltt .gt_indent_5 {
  text-indent: 25px;
}

#innakzbltt .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#innakzbltt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"><caption><p>Table 7 Interactions between duration and sharing of childcare, daily
enjoyment of mothers</p></caption>
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="a-"> <span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Primary">Primary<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Alone">Alone<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Routine">Routine<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Enriched">Enriched<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers=" " class="gt_row gt_left">Father's share &lt;40%</td>
<td headers="Primary" class="gt_row gt_center">-0.01</td>
<td headers="Alone" class="gt_row gt_center">0.04</td>
<td headers="Routine" class="gt_row gt_center">-0.09</td>
<td headers="Enriched" class="gt_row gt_center">0.07</td></tr>
    <tr><td headers=" " class="gt_row gt_left"></td>
<td headers="Primary" class="gt_row gt_center">(0.10)</td>
<td headers="Alone" class="gt_row gt_center">(0.11)</td>
<td headers="Routine" class="gt_row gt_center">(0.10)</td>
<td headers="Enriched" class="gt_row gt_center">(0.09)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Father's share &gt;=40%</td>
<td headers="Primary" class="gt_row gt_center">-0.13</td>
<td headers="Alone" class="gt_row gt_center">-0.25*</td>
<td headers="Routine" class="gt_row gt_center">-0.17</td>
<td headers="Enriched" class="gt_row gt_center">-0.11</td></tr>
    <tr><td headers=" " class="gt_row gt_left"></td>
<td headers="Primary" class="gt_row gt_center">(0.11)</td>
<td headers="Alone" class="gt_row gt_center">(0.11)</td>
<td headers="Routine" class="gt_row gt_center">(0.11)</td>
<td headers="Enriched" class="gt_row gt_center">(0.10)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Father's share &lt;40% X fathers' caring time</td>
<td headers="Primary" class="gt_row gt_center">0.03</td>
<td headers="Alone" class="gt_row gt_center">-0.11</td>
<td headers="Routine" class="gt_row gt_center">-0.08</td>
<td headers="Enriched" class="gt_row gt_center">0.16</td></tr>
    <tr><td headers=" " class="gt_row gt_left"></td>
<td headers="Primary" class="gt_row gt_center">(0.12)</td>
<td headers="Alone" class="gt_row gt_center">(0.14)</td>
<td headers="Routine" class="gt_row gt_center">(0.10)</td>
<td headers="Enriched" class="gt_row gt_center">(0.11)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Father's share &gt;=40% X fathers' caring time</td>
<td headers="Primary" class="gt_row gt_center">0.03</td>
<td headers="Alone" class="gt_row gt_center">0.07</td>
<td headers="Routine" class="gt_row gt_center">0.00</td>
<td headers="Enriched" class="gt_row gt_center">0.04</td></tr>
    <tr><td headers=" " class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;"></td>
<td headers="Primary" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.05)</td>
<td headers="Alone" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.05)</td>
<td headers="Routine" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.07)</td>
<td headers="Enriched" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.04)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Num.Obs.</td>
<td headers="Primary" class="gt_row gt_center">373</td>
<td headers="Alone" class="gt_row gt_center">335</td>
<td headers="Routine" class="gt_row gt_center">370</td>
<td headers="Enriched" class="gt_row gt_center">331</td></tr>
    <tr><td headers=" " class="gt_row gt_left">R2</td>
<td headers="Primary" class="gt_row gt_center">0.057</td>
<td headers="Alone" class="gt_row gt_center">0.072</td>
<td headers="Routine" class="gt_row gt_center">0.061</td>
<td headers="Enriched" class="gt_row gt_center">0.066</td></tr>
    <tr><td headers=" " class="gt_row gt_left">R2 Adj.</td>
<td headers="Primary" class="gt_row gt_center">0.029</td>
<td headers="Alone" class="gt_row gt_center">0.041</td>
<td headers="Routine" class="gt_row gt_center">0.032</td>
<td headers="Enriched" class="gt_row gt_center">0.034</td></tr>
    <tr><td headers=" " class="gt_row gt_left">AIC</td>
<td headers="Primary" class="gt_row gt_center">846.8</td>
<td headers="Alone" class="gt_row gt_center">767.8</td>
<td headers="Routine" class="gt_row gt_center">843.2</td>
<td headers="Enriched" class="gt_row gt_center">754.4</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="5">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Matched household-level dataset of parents aged 16 and above in heterosexual couples with at least one child under 15. data: UK TUS 2015. Coefficients denote the change in the specified well-being scale. Standard errors between brackets.</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<div class="cell tbl-cap-location-top" data-tbl-cap="Table 8 Interactions between duration and sharing of childcare (Life satisfaction of fathers">
<div class="cell-output-display">
<div id="nlokeditvq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#nlokeditvq table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#nlokeditvq thead, #nlokeditvq tbody, #nlokeditvq tfoot, #nlokeditvq tr, #nlokeditvq td, #nlokeditvq th {
  border-style: none;
}

#nlokeditvq p {
  margin: 0;
  padding: 0;
}

#nlokeditvq .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nlokeditvq .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#nlokeditvq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nlokeditvq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nlokeditvq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nlokeditvq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlokeditvq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nlokeditvq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nlokeditvq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nlokeditvq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nlokeditvq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nlokeditvq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nlokeditvq .gt_spanner_row {
  border-bottom-style: hidden;
}

#nlokeditvq .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#nlokeditvq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nlokeditvq .gt_from_md > :first-child {
  margin-top: 0;
}

#nlokeditvq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nlokeditvq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nlokeditvq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#nlokeditvq .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#nlokeditvq .gt_row_group_first td {
  border-top-width: 2px;
}

#nlokeditvq .gt_row_group_first th {
  border-top-width: 2px;
}

#nlokeditvq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlokeditvq .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#nlokeditvq .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#nlokeditvq .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlokeditvq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlokeditvq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nlokeditvq .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#nlokeditvq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nlokeditvq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlokeditvq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nlokeditvq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlokeditvq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nlokeditvq .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlokeditvq .gt_left {
  text-align: left;
}

#nlokeditvq .gt_center {
  text-align: center;
}

#nlokeditvq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nlokeditvq .gt_font_normal {
  font-weight: normal;
}

#nlokeditvq .gt_font_bold {
  font-weight: bold;
}

#nlokeditvq .gt_font_italic {
  font-style: italic;
}

#nlokeditvq .gt_super {
  font-size: 65%;
}

#nlokeditvq .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#nlokeditvq .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#nlokeditvq .gt_indent_1 {
  text-indent: 5px;
}

#nlokeditvq .gt_indent_2 {
  text-indent: 10px;
}

#nlokeditvq .gt_indent_3 {
  text-indent: 15px;
}

#nlokeditvq .gt_indent_4 {
  text-indent: 20px;
}

#nlokeditvq .gt_indent_5 {
  text-indent: 25px;
}

#nlokeditvq .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#nlokeditvq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"><caption><p>Table 8 Interactions between duration and sharing of childcare (Life
satisfaction of fathers</p></caption>
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="a-"> <span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Primary">Primary<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Alone">Alone<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Routine">Routine<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Enriched">Enriched<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers=" " class="gt_row gt_left">Father's share &lt;40%</td>
<td headers="Primary" class="gt_row gt_center">0.16</td>
<td headers="Alone" class="gt_row gt_center">-0.10</td>
<td headers="Routine" class="gt_row gt_center">0.13</td>
<td headers="Enriched" class="gt_row gt_center">0.01</td></tr>
    <tr><td headers=" " class="gt_row gt_left"></td>
<td headers="Primary" class="gt_row gt_center">(0.18)</td>
<td headers="Alone" class="gt_row gt_center">(0.20)</td>
<td headers="Routine" class="gt_row gt_center">(0.18)</td>
<td headers="Enriched" class="gt_row gt_center">(0.17)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Father's share &gt;=40%</td>
<td headers="Primary" class="gt_row gt_center">-0.32+</td>
<td headers="Alone" class="gt_row gt_center">-0.42*</td>
<td headers="Routine" class="gt_row gt_center">-0.06</td>
<td headers="Enriched" class="gt_row gt_center">-0.18</td></tr>
    <tr><td headers=" " class="gt_row gt_left"></td>
<td headers="Primary" class="gt_row gt_center">(0.18)</td>
<td headers="Alone" class="gt_row gt_center">(0.17)</td>
<td headers="Routine" class="gt_row gt_center">(0.21)</td>
<td headers="Enriched" class="gt_row gt_center">(0.15)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Father's share &lt;40% X Fathers' caring time</td>
<td headers="Primary" class="gt_row gt_center">0.13</td>
<td headers="Alone" class="gt_row gt_center">-0.25</td>
<td headers="Routine" class="gt_row gt_center">-0.21*</td>
<td headers="Enriched" class="gt_row gt_center">0.16</td></tr>
    <tr><td headers=" " class="gt_row gt_left"></td>
<td headers="Primary" class="gt_row gt_center">(0.17)</td>
<td headers="Alone" class="gt_row gt_center">(0.19)</td>
<td headers="Routine" class="gt_row gt_center">(0.10)</td>
<td headers="Enriched" class="gt_row gt_center">(0.27)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Father's share &gt;=40% X Fathers' caring time</td>
<td headers="Primary" class="gt_row gt_center">0.16*</td>
<td headers="Alone" class="gt_row gt_center">0.12</td>
<td headers="Routine" class="gt_row gt_center">0.03</td>
<td headers="Enriched" class="gt_row gt_center">0.09</td></tr>
    <tr><td headers=" " class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;"></td>
<td headers="Primary" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.08)</td>
<td headers="Alone" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.11)</td>
<td headers="Routine" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.08)</td>
<td headers="Enriched" class="gt_row gt_center" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">(0.09)</td></tr>
    <tr><td headers=" " class="gt_row gt_left">Num.Obs.</td>
<td headers="Primary" class="gt_row gt_center">290</td>
<td headers="Alone" class="gt_row gt_center">256</td>
<td headers="Routine" class="gt_row gt_center">292</td>
<td headers="Enriched" class="gt_row gt_center">242</td></tr>
    <tr><td headers=" " class="gt_row gt_left">R2</td>
<td headers="Primary" class="gt_row gt_center">0.050</td>
<td headers="Alone" class="gt_row gt_center">0.043</td>
<td headers="Routine" class="gt_row gt_center">0.029</td>
<td headers="Enriched" class="gt_row gt_center">0.040</td></tr>
    <tr><td headers=" " class="gt_row gt_left">R2 Adj.</td>
<td headers="Primary" class="gt_row gt_center">0.012</td>
<td headers="Alone" class="gt_row gt_center">-0.000</td>
<td headers="Routine" class="gt_row gt_center">-0.009</td>
<td headers="Enriched" class="gt_row gt_center">-0.006</td></tr>
    <tr><td headers=" " class="gt_row gt_left">AIC</td>
<td headers="Primary" class="gt_row gt_center">899.0</td>
<td headers="Alone" class="gt_row gt_center">791.3</td>
<td headers="Routine" class="gt_row gt_center">891.9</td>
<td headers="Enriched" class="gt_row gt_center">743.7</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="5">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Matched household-level dataset of parents aged 16 and above in heterosexual couples with at least one child under 15. data: UK TUS 2015. Coefficients denote the change in the specified well-being scale. Standard errors between brackets.</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</section>
<section id="role-of-control-variables" class="level3">
<h3 class="anchored" data-anchor-id="role-of-control-variables">Role of control variables</h3>
<p>Comparing models with and without control variables highlighted several patterns. Controlling for whether caring occurred during a weekday or at the weekend reduces the coefficient and significance of enrichment care on well-being: in other words, the positive impact of fathers spending time on enriched care might in fact be partly due to the fact that it predominantly occurs at the weekend, a time during which daily enjoyment tends to be higher for all.</p>
<p>These findings suggest that greater paternal involvement can enhance maternal enjoyment, but only when mothers themselves are also highly involved in childcare. Conversely, fathers report higher enjoyment when their involvement is more modest relative to their partner.</p>
</section>
</section>
</section>
<section id="discussion-and-conclusion" class="level1">
<h1>Discussion And Conclusion</h1>
<p>This paper has examined the relationship between the division of childcare and parental well-being among dual-earner couples with children, drawing on detailed time-use diary data. Unlike previous studies that rely on perceptions or self-reported frequencies, this approach allowed us to investigate both the actual amount and relative share of childcare time undertaken by fathers. We also explored different types of care (routine, enrichment, primary, solo) and employed an innovative measure of immediate well-being: daily enjoyment, alongside conventional metrics such as life satisfaction and work-life balance.</p>
<p>An important result is that despite increasing societal expectations around father involvement, nearly one-third of fathers in our sample did not report any childcare on the diary day. Moreover, close to half had no solo care responsibilities. Only a minority of fathers undertook an equal or greater share of childcare.</p>
<p>Contrary to some expectations, we did not find consistent evidence that increased paternal involvement improved maternal well-being. In some cases, mothers reported lower enjoyment and life satisfaction when fathers took on a larger share of care. For fathers themselves, the relationship between childcare and well-being was more complex: while high shares of routine or solo care were linked to lower life satisfaction, greater involvement in enrichment and primary care was associated with higher daily enjoyment.</p>
<p>Unpacking these associations by interacting absolute and relative involvement in childcare clarified that a sustained involvement in primary childcare by fathers was associated with higher daily enjoyment among them - even if that may not be the case for specific, less gratifying kinds of care, such as routine childcare. Indeed, similarly to previous studies, we found that fathers enjoyed their day more as they were more intensively involved in enrichment childcare. It may also be that that the negative association is the result of a reverse relationship: some families in which fathers experienced lower life satisfaction, were those where they were taking a larger share of childcare.</p>
<p>These findings suggest that moderate, meaningful involvement - particularly in enrichment childcare - may be most beneficial for fathers. Conversely, a large share of less enjoyable caregiving tasks may negatively affect well-being.</p>
<p>This leads us to an interesting conclusion. Much of the discussion around the sharing of childcare so far has been driven by its impact on gender equality, namely how a more equal distribution of caring roles can help women fully compete with men in the commodified labour market. However, as this study and some previous studies have shown (<span class="citation" data-cites="Ladge2015">Ladge et al. (<a href="#ref-Ladge2015" role="doc-biblioref">2015</a>)</span>; <span class="citation" data-cites="Negraia2020">Negraia and Augustine (<a href="#ref-Negraia2020" role="doc-biblioref">2020</a>)</span>), getting fathers more involved in childcare may also improve men’s (mental) health. Masculinities and men’s identities are shifting as society’s ideas of gender roles change and demands of men and fathers change (<span class="citation" data-cites="Brandth1998">Brandth and Kvande (<a href="#ref-Brandth1998" role="doc-biblioref">1998</a>)</span>; <span class="citation" data-cites="Lyonette2015">Lyonette and Crompton (<a href="#ref-Lyonette2015" role="doc-biblioref">2015</a>)</span>; <span class="citation" data-cites="Elliott2016">Elliott (<a href="#ref-Elliott2016" role="doc-biblioref">2016</a>)</span>). What our study has shown is that we need to think about men’s involvement in childcare as being instrumental to improve their well-being. Men should be allowed to expand their roles as carers not only to ensure that they are able to meet their duties as involved fathers, and equal partners in parenting, but also because it benefits their mental health, and as a result, possibly their overall health and well-being in the long term as well.</p>
<p>These findings also contribute to the literature on maternal well-being. While past research has largely focused on cognitive measures, our study adds emotional and experiential insights. Daily enjoyment, in particular, appears to be more sensitive to changes in childcare division than broader life satisfaction measures. Our study shows that father’s involvement in childcare has a positive impact on the immediate well-being - daily enjoyment - of both parents (see also <span class="citation" data-cites="Negraia2020">Negraia and Augustine (<a href="#ref-Negraia2020" role="doc-biblioref">2020</a>)</span>).</p>
<p>The paper is not without its limitations: the relatively small sample size, which constrains statistical power, and the simplicity of the daily enjoyment measure, which does not capture negative affects or arousal (see <span class="citation" data-cites="Warr2007">Warr (<a href="#ref-Warr2007" role="doc-biblioref">2007</a>)</span>). Future research should replicate these findings with larger samples and improved instruments. Policy implications are substantial. As governments and organizations promote paternity leave and flexible work, our study suggests these initiatives should be framed not only around economic productivity or gender equity, but also around enhancing parental well-being. Fathers who are more involved in childcare may become happier, more balanced, and ultimately more productive workers.</p>
<p>These findings have significant implications for government and corporate policies.</p>
<p>Some governments have been pushing for greater involvement by fathers in the care of their children, for instance, by increasing the size of the fathers-only portion of parental leave (see also the European Commission’s Work-life balance directive). Much of these tend to aim to increase the size of the female workforce and fully exploit the female human capital potential. This paper shows that the conversation also needs to focus on enhancing parental well-being of fathers and men’s in addition to that of mothers. This can reinforce the case for implementing such policies: which are not only necessary for sustaining economic growth or for women’s rights per se, but also to enhance the well-being of both men and women.</p>
<p>Our results also have implications for companies and managers. We know from the organizational studies literature that workers who are happy and have better work-life balance will be more productive in companies (<span class="citation" data-cites="Leslie2012">Leslie et al. (<a href="#ref-Leslie2012" role="doc-biblioref">2012</a>)</span>). Whilst retaining female workers is considered to be the main raison d’être of fathers’ involvement in childcare, this may not provide sufficient incentives for employers of fathers. Increased maternal labour force participation may benefit other companies. However, as we can see from the results of our study, supporting fathers to play a larger role in the care of children can improve their well-being which can directly relate to worker’s productivity.</p>
<p>Finally, our study carries an important message to fathers and mothers. Fathers may be reluctant to use leaves and flexible working arrangements to be more involved in the care of their children due to the stigma it carries (<span class="citation" data-cites="Rudman2013">Rudman and Mescher (<a href="#ref-Rudman2013" role="doc-biblioref">2013</a>)</span>), and for fear of experiencing disadvantage in their career. Lastly, for families, our study offers an encouraging message: sharing caregiving more equally can lead to more satisfying, emotionally rich days for both mothers and fathers. Shifting toward greater co-parenting is not just good for gender equality—it may also be good for everyone’s well-being.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Allen2007a" class="csl-entry" role="listitem">
Allen, and K Daly. 2007. <span>“The Effects of Father Involvement: An Updated Research Summary of the Evidence: Centre for Families.”</span>
</div>
<div id="ref-Baxter2011" class="csl-entry" role="listitem">
Baxter, Jennifer, and Diana Smart. 2011. <span>“Fathering in Australia Among Couple Families with Young Children.”</span> Research report. Australian Department of Families, Housing, Community Services; Indigenous Affairs Occasional paper no 37. <a href="https://ssrn.com/abstract=1776522">https://ssrn.com/abstract=1776522</a>.
</div>
<div id="ref-Blair2024" class="csl-entry" role="listitem">
Blair, Graeme, Jasper Cooper, Alexander Coppock, Macartan Humphreys, and Luke Sonnet. 2024. <em>Estimatr: Fast Estimators for Design-Based Inference</em>. <a href="https://CRAN.R-project.org/package=estimatr">https://CRAN.R-project.org/package=estimatr</a>.
</div>
<div id="ref-Brandth1998" class="csl-entry" role="listitem">
Brandth, Berit, and Elin Kvande. 1998. <span>“Masculinity and Child Care: The Reconstruction of Fathering.”</span> <em>The Sociological Review (Keele)</em> 46 (2): 293–313.
</div>
<div id="ref-Burgess2021" class="csl-entry" role="listitem">
Burgess, Adrienne, and Rebecca Goldman. 2021. <span>“Lockdown Fathers: The Untold Story: Full Report.”</span> Research report. Fatherhood Institute. <a href="https://www.scie-socialcareonline.org.uk/lockdown-fathers-the-untold-story-full-report/r/a116f00000UuYZVAA3">https://www.scie-socialcareonline.org.uk/lockdown-fathers-the-untold-story-full-report/r/a116f00000UuYZVAA3</a>.
</div>
<div id="ref-Carlson2016" class="csl-entry" role="listitem">
Carlson, Daniel L., Sarah Hanson, and Andrea Fitzroy. 2016. <span>“The Division of Child Care, Sexual Intimacy, and Relationship Quality in Couples.”</span> <em>Gender &amp; Society</em> 30 (3): 442–66.
</div>
<div id="ref-Chandola2019" class="csl-entry" role="listitem">
Chandola, Tarani, Cara L Booker, Meena Kumari, and Michaela Benzeval. 2019. <span>“Are Flexible Work Arrangements Associated with Lower Levels of Chronic Stress-Related Biomarkers? A Study of 6025 Employees in the UK Household Longitudinal Study.”</span> <em>Sociology (Oxford)</em> 53 (4): 779–99.
</div>
<div id="ref-Chung2021" class="csl-entry" role="listitem">
Chung, H. 2021. <span>“Shared Care, Father’s Involvement in Care and Family Well-Being Outcomes: A Literature Review.”</span> <em>Report for the Government Equalities Office</em>.
</div>
<div id="ref-Craig2006" class="csl-entry" role="listitem">
Craig, Lyn. 2006. <span>“Does Father Care Mean Fathers Share? A Comparison of How Mothers and Fathers in Intact Families Spend Time with Children.”</span> <em>Gender &amp; Society</em> 20 (2): 259–81.
</div>
<div id="ref-Craig2011a" class="csl-entry" role="listitem">
Craig, Lyn, and Killian Mullan. 2011. <span>“How Mothers and Fathers Share Childcare: A Cross-National Time-Use Comparison.”</span> <em>American Sociological Review</em> 76 (6): 834–61.
</div>
<div id="ref-Craig2011" class="csl-entry" role="listitem">
Craig, Lyn, and Abigail Powell. 2011. <span>“Non-Standard Work Schedules, Work-Family Balance and the Gendered Division of Childcare.”</span> <em>Work, Employment and Society</em> 25 (2): 274–91.
</div>
<div id="ref-Craig2014" class="csl-entry" role="listitem">
Craig, Lyn, Abigail Powell, and Ciara Smyth. 2014. <span>“Towards Intensive Parenting? Changes in the Composition and Determinants of Mothers’ and Fathers’ Time with Children 1992-2006.”</span> <em>The British Journal of Sociology</em> 65 (3): 555–79.
</div>
<div id="ref-Diener1999" class="csl-entry" role="listitem">
Diener, E, EM Suh, RE Lucas, and HL Smith. 1999. <span>“Subjective Well-Being: Three Decades of Progress.”</span> <em>Psychological Bulletin</em> 125 (2): 276–302.
</div>
<div id="ref-Dotti2016" class="csl-entry" role="listitem">
Dotti Sani, Giulia M., and Judith Treas. 2016. <span>“Educational Gradients in Parents’ Child-Care Time Across Countries, 1965–2012.”</span> <em>Journal of Marriage and Family</em> 78 (4): 1083–96. https://doi.org/<a href="https://doi.org/10.1111/jomf.12305">https://doi.org/10.1111/jomf.12305</a>.
</div>
<div id="ref-Elliott2016" class="csl-entry" role="listitem">
Elliott, Karla. 2016. <span>“Caring Masculinities: Theorizing an Emerging Concept.”</span> <em>Men and Masculinities</em> 19 (3): 240–59.
</div>
<div id="ref-Fatherhood2016" class="csl-entry" role="listitem">
Fatherhood Institute. 2016. <span>“2016 Fairness in Families Index.”</span> London: Fatherhood Institute.
</div>
<div id="ref-Frisco2003" class="csl-entry" role="listitem">
Frisco, Michelle L., and Kristi Williams. 2003. <span>“Perceived Housework Equity, Marital Happiness, and Divorce in Dual-Earner Households.”</span> <em>Journal of Family Issues</em> 24 (1): 51–73.
</div>
<div id="ref-Glass2016" class="csl-entry" role="listitem">
Glass, Jennifer, Matthew A. Andersson, and Robin W. Simon. 2016. <span>“Parenthood and Happiness: Effects of Work-Family Reconciliation Policies in 22 OECD Countries.”</span> <em>The American Journal of Sociology</em> 122 (3): 886–929.
</div>
<div id="ref-GEO2019" class="csl-entry" role="listitem">
Government Equalities Office. 2019. <span>“The Case for Change: How Economic Gender Inequalities Develop Across the Life Course.”</span>
</div>
<div id="ref-Gracia2015" class="csl-entry" role="listitem">
Gracia, Pablo, and Gøsta Esping-Andersen. 2015. <span>“Fathers’ Child Care Time and Mothers’ Paid Work: A Cross-National Study of Denmark, Spain, and the United Kingdom.”</span> <em>Family Science</em> 6 (1): 270–81. <a href="https://doi.org/10.1080/19424620.2015.1082336">https://doi.org/10.1080/19424620.2015.1082336</a>.
</div>
<div id="ref-Hochschild1989" class="csl-entry" role="listitem">
Hochschild, Arlie Russell. 1989. <em>The Second Shift: Working Families and the Revolution at Home</em>. New York: Penguin Publishing Group.
</div>
<div id="ref-Huerta2014" class="csl-entry" role="listitem">
Huerta, Maria C., Willem Adema, Jennifer Baxter, Wen-Jui Han, Mette Lausten, Raehyuck Lee, and Jane Waldfogel. 2014. <span>“Fathers’ Leave and Fathers’ Involvement: Evidence from Four OECD Countries.”</span> <em>European Journal of Social Security</em> 16 (4): 308–46.
</div>
<div id="ref-Kalmijn1999" class="csl-entry" role="listitem">
Kalmijn, Matthijs. 1999. <span>“Father Involvement in Childrearing and the Perceived Stability of Marriage.”</span> <em>Journal of Marriage and Family</em> 61 (2): 409–21.
</div>
<div id="ref-Kelland2022" class="csl-entry" role="listitem">
Kelland, Jasmine, Duncan Lewis, and Virginia Fisher. 2022. <span>“Viewed with Suspicion, Considered Idle and Mocked‐working Caregiving Fathers and Fatherhood Forfeits.”</span> <em>Gender, Work, and Organization</em> 29 (5): 1578–93.
</div>
<div id="ref-Kroll2016" class="csl-entry" role="listitem">
Kroll, Mary E., Claire Carson, Maggie Redshaw, and Maria A. Quigley. 2016. <span>“Early Father Involvement and Subsequent Child Behaviour at Ages 3, 5 and 7 Years: Prospective Analysis of the UK Millennium Cohort Study.”</span> <em>PloS One</em> 11 (9): e0162339–39.
</div>
<div id="ref-Ladge2015" class="csl-entry" role="listitem">
Ladge, Jamie J., Beth K. Humberd, Marla Baskerville Watkins, and Brad Harrington. 2015. <span>“UPDATING THE ORGANIZATION MAN: AN EXAMINATION OF INVOLVED FATHERING IN THE WORKPLACE.”</span> <em>Academy of Management Perspectives</em> 29 (1): 152–71.
</div>
<div id="ref-Leslie2012" class="csl-entry" role="listitem">
Leslie, Lisa M., Colleen Flaherty Manchester, Tae-Youn Park, and S. I. Ahn Mehng. 2012. <span>“Flexible Work Practices: A Source of Career Premiums or Penalties?”</span> 55: 1407–28. <a href="https://doi.org/10.5465/amj.2010.0651">https://doi.org/10.5465/amj.2010.0651</a>.
</div>
<div id="ref-Lyonette2015" class="csl-entry" role="listitem">
Lyonette, Clare, and Rosemary Crompton. 2015. <span>“Sharing the Load? Partners’ Relative Earnings and the Division of Domestic Labour.”</span> <em>Work, Employment and Society</em> 29 (1): 23–40.
</div>
<div id="ref-Lyubomirsky2005" class="csl-entry" role="listitem">
Lyubomirsky, Sonja, Laura King, and Ed Diener. 2005. <span>“The Benefits of Frequent Positive Affect: Does Happiness Lead to Success?”</span> <em>Psychological Bulletin</em> 131 (6): 803–55.
</div>
<div id="ref-Milkie2002" class="csl-entry" role="listitem">
Milkie, Melissa A., Suzanne M. Bianchi, Marybeth J. Mattingly, and John P. Robinson. 2002. <span>“Gendered Division of Childrearing: Ideals, Realities, and the Relationship to Parental Well-Being.”</span> <em>Sex Roles</em> 47 (1-2): 21–38.
</div>
<div id="ref-Negraia2020" class="csl-entry" role="listitem">
Negraia, Daniela Veronica, and Jennifer March Augustine. 2020. <span>“Unpacking the Parenting Well-Being Gap: The Role of Dynamic Features of Daily Life Across Broader Social Contexts.”</span> <em>Social Psychology Quarterly</em> 83 (3): 207–28.
</div>
<div id="ref-Nomaguchi2003" class="csl-entry" role="listitem">
Nomaguchi, Kei M., and Melissa A. Milkie. 2003. <span>“Costs and Rewards of Children: The Effects of Becoming a Parent on Adults’ Lives.”</span> <em>Journal of Marriage and Family</em> 65 (2): 356–74.
</div>
<div id="ref-Nomaguchi2017" class="csl-entry" role="listitem">
Nomaguchi, Kei, Susan Brown, and Tanya M. Leyman. 2017. <span>“Fathers’ Participation in Parenting and Maternal Parenting Stress: Variation by Relationship Status.”</span> <em>Journal of Family Issues</em> 38 (8): 1132–56.
</div>
<div id="ref-Norman2018" class="csl-entry" role="listitem">
Norman, Helen, Mark Elliot, and Colette Fagan. 2018. <span>“Does Fathers’ Involvement in Childcare and Housework Affect Couples’ Relationship Stability?”</span> <em>Social Science Quarterly</em> 99 (5): 1599–1613.
</div>
<div id="ref-ONS2020" class="csl-entry" role="listitem">
ONS. 2020. <span>“Parenting in Lockdown: Coronavirus and the Effects on Work-Life Balance.”</span> Edited by Office for National Statistics. London.
</div>
<div id="ref-Pressman2005" class="csl-entry" role="listitem">
Pressman, Sarah D, and Sheldon Cohen. 2005. <span>“Does Positive Affect Influence Health?”</span> <em>Psychological Bulletin</em> 131 (6): 925–71.
</div>
<div id="ref-Rudman2013" class="csl-entry" role="listitem">
Rudman, Laurie A., and Kris Mescher. 2013. <span>“Penalizing Men Who Request a Family Leave: Is Flexibility Stigma a Femininity Stigma? Feminizing Male Leave Requesters”</span> 69: 322–40. <a href="https://doi.org/10.1111/josi.12017">https://doi.org/10.1111/josi.12017</a>.
</div>
<div id="ref-Ruppanner2018" class="csl-entry" role="listitem">
Ruppanner, Leah, Maria Brandén, and Jani Turunen. 2018. <span>“Does Unequal Housework Lead to Divorce? Evidence from Sweden.”</span> <em>Sociology (Oxford)</em> 52 (1): 75–94.
</div>
<div id="ref-Schober2012" class="csl-entry" role="listitem">
Schober, Pia S. 2012. <span>“Paternal Child Care and Relationship Quality: A Longitudinal Analysis of Reciprocal Associations.”</span> <em>Journal of Marriage and Family</em> 74 (2): 281–96.
</div>
<div id="ref-Schober2013" class="csl-entry" role="listitem">
———. 2013. <span>“Gender Equality and Outsourcing of Domestic Work, Childbearing, and Relationship Stability Among British Couples.”</span> <em>Journal of Family Issues</em> 34 (1): 25–52.
</div>
<div id="ref-Schober2016" class="csl-entry" role="listitem">
Schober, Pia S., and Juliane F. Stahl. 2016. <span>“Expansion of Full-Day Childcare and Subjective Well-Being of Mothers: Interdependencies with Culture and Resources.”</span> <em>European Sociological Review</em> 32 (5): 593–606.
</div>
<div id="ref-Scott2013" class="csl-entry" role="listitem">
Scott, &amp; Clery, J. 2013. <span>“Gender Roles: An Incomplete Revolution?”</span> In <em>British Social Attitudes: The 30th Report</em>, edited by A Park, C Bryson, E Clery, and J Curtice, 115–38. London: NatCen Social Research.
</div>
<div id="ref-Taylor2018" class="csl-entry" role="listitem">
Taylor, &amp; Scott, E. A. 2018. <span>“Gender: New Consensus or Continuing Battleground?”</span> In <em>British Social Attitudes: The 35th Report</em>, edited by M. Phillips D. Phillips J. Curtice, 1–30. London: NatCen Social Research.
</div>
<div id="ref-Twamley2013" class="csl-entry" role="listitem">
Twamley, Katherine, Ginny Brunton, Katy Sutcliffe, Kate Hinds, and James Thomas. 2013. <span>“Fathers’ Involvement and the Impact on Family Mental Health: Evidence from Millennium Cohort Study Analyses.”</span> <em>Community, Work &amp; Family</em> 16 (2): 212–24.
</div>
<div id="ref-Walzer1996" class="csl-entry" role="listitem">
Walzer, Susan. 1996. <span>“Thinking about the Baby: Gender and Divisions of Infant Care.”</span> <em>Social Problems (Berkeley, Calif.)</em> 43 (2): 219–34.
</div>
<div id="ref-Warr2007" class="csl-entry" role="listitem">
Warr, Peter. 2007. <em>Work, Happiness, and Unhappiness</em>. Mahwah, N.J: Lawrence Erlbaum.
</div>
<div id="ref-Working2017" class="csl-entry" role="listitem">
Working Families. 2017. <span>“Modern Family Index.”</span> Research report. London: Working Families.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>